import { mutation } from "./_generated/server";

/**
 * Real product seed data scraped from Algerian PC retailers (wifidjelfa.com)
 * Run: npx convex run seedReal:default
 */

const HIERARCHY = [
  {
    slug: "pc-components", nameFr: "Composants PC", nameAr: "مكونات الكمبيوتر", icon: "memory", order: 1,
    children: [
      { slug: "processors", nameFr: "Processeurs", nameAr: "المعالجات", icon: "developer_board", order: 1 },
      { slug: "ram", nameFr: "Mémoire RAM", nameAr: "الذاكرة العشوائية", icon: "memory_alt", order: 2 },
      { slug: "motherboards", nameFr: "Cartes mères", nameAr: "اللوحات الأم", icon: "dashboard", order: 3 },
      { slug: "cpu-cooling", nameFr: "Refroidissement CPU", nameAr: "تبريد المعالج", icon: "ac_unit", order: 4 },
      { slug: "cases", nameFr: "Boîtiers", nameAr: "الصناديق", icon: "view_in_ar", order: 5 },
      { slug: "graphics-cards", nameFr: "Cartes graphiques", nameAr: "بطاقات الرسوميات", icon: "videocam", order: 6 },
      { slug: "power-supplies", nameFr: "Alimentations", nameAr: "مزودات الطاقة", icon: "bolt", order: 7 },
    ],
  },
  {
    slug: "storage-devices", nameFr: "Stockage", nameAr: "أجهزة التخزين", icon: "storage", order: 2,
    children: [
      { slug: "hard-drives", nameFr: "Disques durs", nameAr: "الأقراص الصلبة", icon: "hard_drive", order: 1 },
      { slug: "ssds", nameFr: "SSD", nameAr: "أقراص SSD", icon: "speed", order: 2 },
      { slug: "usb-flash-drives", nameFr: "Clés USB & cartes mémoire", nameAr: "فلاش USB وبطاقات الذاكرة", icon: "usb", order: 3 },
      { slug: "optical-drives", nameFr: "Lecteurs optiques", nameAr: "محركات الأقراص الضوئية", icon: "album", order: 4 },
    ],
  },
  {
    slug: "peripherals", nameFr: "Périphériques", nameAr: "الأجهزة الطرفية", icon: "monitor", order: 3,
    children: [
      { slug: "monitors", nameFr: "Moniteurs", nameAr: "الشاشات", icon: "monitor", order: 1 },
      { slug: "headsets", nameFr: "Casques & écouteurs", nameAr: "سماعات الرأس", icon: "headphones", order: 2 },
      { slug: "mice", nameFr: "Souris", nameAr: "الفأرات", icon: "mouse", order: 3 },
      { slug: "mouse-pads", nameFr: "Tapis de souris", nameAr: "لوحات الفأرة", icon: "grid_view", order: 4 },
      { slug: "keyboards", nameFr: "Claviers", nameAr: "لوحات المفاتيح", icon: "keyboard", order: 5 },
      { slug: "game-controllers", nameFr: "Manettes de jeu", nameAr: "أذرع التحكم", icon: "sports_esports", order: 6 },
      { slug: "microphones", nameFr: "Microphones", nameAr: "الميكروفونات", icon: "mic", order: 7 },
      { slug: "speakers", nameFr: "Haut-parleurs", nameAr: "مكبرات الصوت", icon: "speaker", order: 8 },
      { slug: "webcams", nameFr: "Webcams", nameAr: "كاميرات الويب", icon: "videocam", order: 9 },
      { slug: "power-protection", nameFr: "Protection électrique", nameAr: "الحماية الكهربائية", icon: "electric_bolt", order: 10 },
      { slug: "projectors", nameFr: "Projecteurs", nameAr: "أجهزة العرض", icon: "cast", order: 11 },
    ],
  },
  {
    slug: "desktops", nameFr: "Ordinateurs de bureau", nameAr: "أجهزة الكمبيوتر المكتبية", icon: "computer", order: 4,
    children: [
      { slug: "gaming-desktops", nameFr: "PC Gaming", nameAr: "أجهزة الألعاب", icon: "sports_esports", order: 1 },
      { slug: "desktop-computers", nameFr: "Ordinateurs de bureau", nameAr: "أجهزة الكمبيوتر المكتبية", icon: "computer", order: 2 },
      { slug: "all-in-one-computers", nameFr: "Tout-en-un", nameAr: "أجهزة الكل في واحد", icon: "desktop_windows", order: 3 },
      { slug: "mini-pcs", nameFr: "Mini PC & Chromebox", nameAr: "أجهزة ميني PC", icon: "devices", order: 4 },
      { slug: "gaming-consoles", nameFr: "Consoles de jeu", nameAr: "أجهزة الألعاب المنزلية", icon: "videogame_asset", order: 5 },
    ],
  },
  {
    slug: "laptops", nameFr: "Ordinateurs portables", nameAr: "أجهزة الكمبيوتر المحمولة", icon: "laptop_mac", order: 5,
    children: [
      { slug: "laptops-notebooks", nameFr: "Portables & Notebooks", nameAr: "أجهزة الكمبيوتر المحمولة", icon: "laptop_mac", order: 1 },
      { slug: "tablets-smartphones", nameFr: "Tablettes & Smartphones", nameAr: "الأجهزة اللوحية والهواتف", icon: "tablet_mac", order: 2 },
      { slug: "laptop-accessories", nameFr: "Accessoires portables", nameAr: "ملحقات الأجهزة المحمولة", icon: "laptop_chromebook", order: 3 },
    ],
  },
  {
    slug: "printers-scanners", nameFr: "Imprimantes & Scanners", nameAr: "الطابعات والماسحات الضوئية", icon: "print", order: 6,
    children: [
      { slug: "laser-inkjet-printers", nameFr: "Imprimantes laser & jet d'encre", nameAr: "طابعات ليزر وحبر", icon: "print", order: 1 },
      { slug: "printer-ink-toner", nameFr: "Encre & toner", nameAr: "حبر وتونر الطابعات", icon: "ink_pen", order: 2 },
      { slug: "printer-paper", nameFr: "Papier d'impression", nameAr: "ورق الطباعة", icon: "description", order: 3 },
    ],
  },
  {
    slug: "accessories", nameFr: "Accessoires", nameAr: "الملحقات", icon: "extension", order: 7,
    children: [
      { slug: "adapters", nameFr: "Adaptateurs", nameAr: "المحولات", icon: "settings_input_hdmi", order: 1 },
      { slug: "cables", nameFr: "Câbles", nameAr: "الكابلات", icon: "cable", order: 2 },
      { slug: "computer-accessories", nameFr: "Accessoires informatiques", nameAr: "ملحقات الكمبيوتر", icon: "devices_other", order: 3 },
      { slug: "hubs", nameFr: "Hubs & docks", nameAr: "موزعات USB", icon: "hub", order: 4 },
      { slug: "sound-cards", nameFr: "Cartes son", nameAr: "بطاقات الصوت", icon: "graphic_eq", order: 5 },
    ],
  },
  {
    slug: "networking", nameFr: "Réseau", nameAr: "الشبكات", icon: "router", order: 8,
    children: [
      { slug: "modems-routers", nameFr: "Modems & routeurs", nameAr: "مودم وراوتر", icon: "router", order: 1 },
      { slug: "network-media-players", nameFr: "Lecteurs multimédia réseau", nameAr: "مشغلات الوسائط", icon: "cast_connected", order: 2 },
      { slug: "network-switches", nameFr: "Commutateurs réseau", nameAr: "محولات الشبكة", icon: "device_hub", order: 3 },
      { slug: "wireless-adapters", nameFr: "Adaptateurs sans fil", nameAr: "محولات لاسلكية", icon: "wifi", order: 4 },
      { slug: "wireless-range-extenders", nameFr: "Répéteurs WiFi", nameAr: "موسعات نطاق WiFi", icon: "signal_wifi_4_bar", order: 5 },
    ],
  },
  {
    slug: "furniture", nameFr: "Mobilier bureau & gaming", nameAr: "أثاث المكتب والألعاب", icon: "chair", order: 9,
    children: [
      { slug: "gaming-chairs", nameFr: "Chaises gaming", nameAr: "كراسي الألعاب", icon: "chair", order: 1 },
      { slug: "office-chairs", nameFr: "Chaises de bureau", nameAr: "كراسي المكتب", icon: "chair_alt", order: 2 },
      { slug: "office-furniture", nameFr: "Mobilier de bureau", nameAr: "أثاث المكتب", icon: "desk", order: 3 },
    ],
  },
];

type ProductSeed = {
  slug: string;
  categorySlug: string;
  brand: string;
  nameFr: string;
  nameAr: string;
  descFr: string;
  descAr: string;
  priceDzd: number;
  stock: number;
  images: string[];
  featured: boolean;
  specs: any;
};

const PRODUCTS: ProductSeed[] = [
  // ============ PROCESSORS ============
  {
    slug: "amd-ryzen-7-9800x3d",
    categorySlug: "processors",
    brand: "AMD",
    nameFr: "AMD Ryzen 7 9800X3D 8C/16T 5.2GHz Gaming",
    nameAr: "AMD Ryzen 7 9800X3D معالج ألعاب",
    descFr: "Le meilleur processeur gaming grâce au 3D V-Cache. 8 cœurs, 16 threads, jusqu'à 5.2 GHz. Socket AM5.",
    descAr: "أفضل معالج ألعاب بفضل تقنية 3D V-Cache. 8 أنوية، 16 خيط، حتى 5.2 جيجاهرتز. مقبس AM5.",
    priceDzd: 107900,
    stock: 4,
    images: ["https://wifidjelfa.com/wp-content/uploads/2026/01/101706070455484444.jpg"],
    featured: true,
    specs: { type: "cpu", socket: "AM5", tdp: 120, cores: 8 },
  },
  {
    slug: "amd-ryzen-9-9900x",
    categorySlug: "processors",
    brand: "AMD",
    nameFr: "AMD Ryzen 9 9900X 12C/24T 5.6GHz",
    nameAr: "AMD Ryzen 9 9900X معالج 12 نواة",
    descFr: "Processeur Zen 5 haut de gamme. 12 cœurs, 24 threads, jusqu'à 5.6 GHz. Socket AM5.",
    descAr: "معالج Zen 5 عالي الأداء. 12 نواة، 24 خيط، حتى 5.6 جيجاهرتز. مقبس AM5.",
    priceDzd: 93900,
    stock: 6,
    images: ["https://wifidjelfa.com/wp-content/uploads/2026/01/101720483912744966.jpg"],
    featured: true,
    specs: { type: "cpu", socket: "AM5", tdp: 120, cores: 12 },
  },
  {
    slug: "amd-ryzen-7-7800x3d",
    categorySlug: "processors",
    brand: "AMD",
    nameFr: "AMD Ryzen 7 7800X3D 8C/16T 5.0GHz Gaming",
    nameAr: "AMD Ryzen 7 7800X3D معالج ألعاب",
    descFr: "Processeur gaming 3D V-Cache. 8 cœurs, 16 threads, jusqu'à 5.0 GHz. Socket AM5.",
    descAr: "معالج ألعاب 3D V-Cache. 8 أنوية، 16 خيط، حتى 5.0 جيجاهرتز. مقبس AM5.",
    priceDzd: 91900,
    stock: 5,
    images: ["https://wifidjelfa.com/wp-content/uploads/2026/01/101706070455484441.jpg"],
    featured: true,
    specs: { type: "cpu", socket: "AM5", tdp: 120, cores: 8 },
  },
  {
    slug: "intel-core-ultra-7-265k",
    categorySlug: "processors",
    brand: "Intel",
    nameFr: "Intel Core Ultra 7 265K 5.5GHz Unlocked",
    nameAr: "Intel Core Ultra 7 265K معالج غير مقفل",
    descFr: "Processeur Intel Arrow Lake débloqué. 30 Mo de cache, jusqu'à 5.50 GHz. Socket LGA1851.",
    descAr: "معالج Intel Arrow Lake غير مقفل. 30 ميجابايت كاش، حتى 5.50 جيجاهرتز. مقبس LGA1851.",
    priceDzd: 86900,
    stock: 7,
    images: ["https://wifidjelfa.com/wp-content/uploads/2025/09/101562290402230274.jpg"],
    featured: false,
    specs: { type: "cpu", socket: "LGA1851", tdp: 125, cores: 20 },
  },
  {
    slug: "intel-core-i7-14700kf",
    categorySlug: "processors",
    brand: "Intel",
    nameFr: "Intel Core i7-14700KF 20C/28T 5.6GHz",
    nameAr: "Intel Core i7-14700KF معالج 20 نواة",
    descFr: "20 cœurs (8P+12E), 28 threads, jusqu'à 5.6 GHz. Socket LGA1700.",
    descAr: "20 نواة (8P+12E)، 28 خيط، حتى 5.6 جيجاهرتز. مقبس LGA1700.",
    priceDzd: 84900,
    stock: 8,
    images: ["https://wifidjelfa.com/wp-content/uploads/2026/02/101752165034361089.jpg"],
    featured: false,
    specs: { type: "cpu", socket: "LGA1700", tdp: 125, cores: 20 },
  },
  {
    slug: "intel-core-ultra-7-265kf",
    categorySlug: "processors",
    brand: "Intel",
    nameFr: "Intel Core Ultra 7 265KF 5.5GHz",
    nameAr: "Intel Core Ultra 7 265KF",
    descFr: "Arrow Lake sans iGPU, 30 Mo cache, jusqu'à 5.50 GHz. Socket LGA1851.",
    descAr: "Arrow Lake بدون رسوميات مدمجة، 30 ميجابايت كاش، حتى 5.50 جيجاهرتز. مقبس LGA1851.",
    priceDzd: 75900,
    stock: 10,
    images: ["https://wifidjelfa.com/wp-content/uploads/2026/03/101800349114826893.jpg"],
    featured: false,
    specs: { type: "cpu", socket: "LGA1851", tdp: 125, cores: 20 },
  },
  {
    slug: "intel-core-ultra-5-245k",
    categorySlug: "processors",
    brand: "Intel",
    nameFr: "Intel Core Ultra 5 245K 5.2GHz",
    nameAr: "Intel Core Ultra 5 245K",
    descFr: "Arrow Lake milieu de gamme. 24 Mo cache, jusqu'à 5.20 GHz. Socket LGA1851.",
    descAr: "Arrow Lake متوسط الفئة. 24 ميجابايت كاش، حتى 5.20 جيجاهرتز. مقبس LGA1851.",
    priceDzd: 65900,
    stock: 9,
    images: ["https://wifidjelfa.com/wp-content/uploads/2025/08/101502848809828356.jpg"],
    featured: false,
    specs: { type: "cpu", socket: "LGA1851", tdp: 125, cores: 14 },
  },
  {
    slug: "amd-ryzen-7-8700g",
    categorySlug: "processors",
    brand: "AMD",
    nameFr: "AMD Ryzen 7 8700G 8C/16T APU Radeon 780M",
    nameAr: "AMD Ryzen 7 8700G معالج مع رسوميات مدمجة",
    descFr: "APU avec Radeon 780M intégré. 8 cœurs, 16 threads, socket AM5, TDP 65W.",
    descAr: "معالج مع Radeon 780M مدمج. 8 أنوية، 16 خيط، مقبس AM5، استهلاك 65 واط.",
    priceDzd: 63400,
    stock: 12,
    images: ["https://wifidjelfa.com/wp-content/uploads/2026/01/101743501850443824.jpg"],
    featured: false,
    specs: { type: "cpu", socket: "AM5", tdp: 65, cores: 8 },
  },
  {
    slug: "amd-ryzen-5-9600x",
    categorySlug: "processors",
    brand: "AMD",
    nameFr: "AMD Ryzen 5 9600X 6C/12T 5.4GHz",
    nameAr: "AMD Ryzen 5 9600X معالج 6 أنوية",
    descFr: "Zen 5 milieu de gamme excellent. 6 cœurs, 12 threads, jusqu'à 5.4 GHz. Socket AM5.",
    descAr: "Zen 5 متوسط الفئة ممتاز. 6 أنوية، 12 خيط، حتى 5.4 جيجاهرتز. مقبس AM5.",
    priceDzd: 51900,
    stock: 15,
    images: ["https://wifidjelfa.com/wp-content/uploads/2026/03/101800349114826777.jpg"],
    featured: false,
    specs: { type: "cpu", socket: "AM5", tdp: 65, cores: 6 },
  },

  // ============ GRAPHICS CARDS ============
  {
    slug: "zotac-rtx-5080-solid-core",
    categorySlug: "graphics-cards",
    brand: "ZOTAC",
    nameFr: "ZOTAC Gaming GeForce RTX 5080 SOLID CORE 16GB",
    nameAr: "ZOTAC Gaming GeForce RTX 5080 16GB",
    descFr: "Carte graphique RTX 5080 Blackwell 16 Go GDDR7. Performance 4K ultime avec DLSS 4.",
    descAr: "بطاقة رسوميات RTX 5080 بلاكويل 16 جيجابايت GDDR7. أداء 4K فائق مع DLSS 4.",
    priceDzd: 344900,
    stock: 3,
    images: ["https://wifidjelfa.com/wp-content/uploads/2026/03/101797479304921102.jpg"],
    featured: true,
    specs: { type: "gpu", tdp: 360, lengthMm: 310, powerConnectors: "16-pin" },
  },
  {
    slug: "zotac-rtx-4080-super-trinity",
    categorySlug: "graphics-cards",
    brand: "ZOTAC",
    nameFr: "ZOTAC GeForce RTX 4080 SUPER Trinity Black 16GB",
    nameAr: "ZOTAC GeForce RTX 4080 SUPER Trinity Black 16GB",
    descFr: "RTX 4080 SUPER avec design triple ventilateur. 16 Go GDDR6X pour le gaming 4K.",
    descAr: "RTX 4080 SUPER بتصميم ثلاثي المراوح. 16 جيجابايت GDDR6X للألعاب بدقة 4K.",
    priceDzd: 299900,
    stock: 4,
    images: ["https://wifidjelfa.com/wp-content/uploads/2025/07/101457911053549608.jpg"],
    featured: true,
    specs: { type: "gpu", tdp: 320, lengthMm: 306, powerConnectors: "16-pin" },
  },
  {
    slug: "sapphire-rx-9070-xt",
    categorySlug: "graphics-cards",
    brand: "Sapphire",
    nameFr: "SAPPHIRE Radeon RX 9070 XT OC 16GB GDDR6",
    nameAr: "SAPPHIRE Radeon RX 9070 XT OC 16GB",
    descFr: "Radeon RX 9070 XT overclockée. 16 Go GDDR6, RDNA 4, excellente en 1440p et 4K.",
    descAr: "Radeon RX 9070 XT مكسورة السرعة. 16 جيجابايت GDDR6، RDNA 4، ممتازة في 1440p و4K.",
    priceDzd: 229000,
    stock: 5,
    images: ["https://wifidjelfa.com/wp-content/uploads/2026/03/101800349114826883.jpg"],
    featured: true,
    specs: { type: "gpu", tdp: 300, lengthMm: 290, powerConnectors: "2x8-pin" },
  },
  {
    slug: "gigabyte-rtx-5070-eagle-oc",
    categorySlug: "graphics-cards",
    brand: "GIGABYTE",
    nameFr: "GIGABYTE GeForce RTX 5070 EAGLE OC SFF 12GB",
    nameAr: "GIGABYTE GeForce RTX 5070 EAGLE OC 12GB",
    descFr: "RTX 5070 compacte SFF. 12 Go GDDR7, DLSS 4, parfaite pour les boîtiers compacts.",
    descAr: "RTX 5070 مدمجة SFF. 12 جيجابايت GDDR7، DLSS 4، مثالية للصناديق المدمجة.",
    priceDzd: 189000,
    stock: 4,
    images: ["https://wifidjelfa.com/wp-content/uploads/2026/04/101851018068754437.jpg"],
    featured: false,
    specs: { type: "gpu", tdp: 250, lengthMm: 242, powerConnectors: "16-pin" },
  },
  {
    slug: "xfx-rx-7900-xt",
    categorySlug: "graphics-cards",
    brand: "XFX",
    nameFr: "XFX AMD Radeon RX 7900 XT 20GB GDDR6 RDNA 3",
    nameAr: "XFX AMD Radeon RX 7900 XT 20GB",
    descFr: "Radeon RX 7900 XT avec 20 Go GDDR6. RDNA 3, excellente pour le gaming 4K.",
    descAr: "Radeon RX 7900 XT مع 20 جيجابايت GDDR6. RDNA 3، ممتازة للألعاب بدقة 4K.",
    priceDzd: 168000,
    stock: 3,
    images: ["https://wifidjelfa.com/wp-content/uploads/2025/10/101614480546332699.jpg"],
    featured: false,
    specs: { type: "gpu", tdp: 300, lengthMm: 322, powerConnectors: "2x8-pin" },
  },
  {
    slug: "pny-rtx-4070-super-verto",
    categorySlug: "graphics-cards",
    brand: "PNY",
    nameFr: "PNY GeForce RTX 4070 SUPER VERTO 12GB OC",
    nameAr: "PNY GeForce RTX 4070 SUPER 12GB",
    descFr: "RTX 4070 SUPER 12 Go GDDR6X. Le meilleur choix en 1440p.",
    descAr: "RTX 4070 SUPER 12 جيجابايت GDDR6X. الخيار الأفضل في 1440p.",
    priceDzd: 159900,
    stock: 6,
    images: ["https://wifidjelfa.com/wp-content/uploads/2025/12/101669562914701461.jpg"],
    featured: false,
    specs: { type: "gpu", tdp: 220, lengthMm: 268, powerConnectors: "1x16-pin" },
  },
  {
    slug: "zotac-rtx-5060-ti-16g",
    categorySlug: "graphics-cards",
    brand: "ZOTAC",
    nameFr: "ZOTAC GeForce RTX 5060 Ti 16GB Twin Edge",
    nameAr: "ZOTAC GeForce RTX 5060 Ti 16GB",
    descFr: "RTX 5060 Ti 16 Go GDDR7. Excellente pour le 1080p et 1440p avec DLSS 4.",
    descAr: "RTX 5060 Ti 16 جيجابايت GDDR7. ممتازة لدقة 1080p و1440p مع DLSS 4.",
    priceDzd: 149900,
    stock: 7,
    images: ["https://wifidjelfa.com/wp-content/uploads/2026/02/101752165034360890.jpg"],
    featured: false,
    specs: { type: "gpu", tdp: 180, lengthMm: 252, powerConnectors: "1x8-pin" },
  },
  {
    slug: "gigabyte-rtx-5060-ti-gaming-oc",
    categorySlug: "graphics-cards",
    brand: "GIGABYTE",
    nameFr: "GIGABYTE GeForce RTX 5060 Ti GAMING OC 8GB GDDR7",
    nameAr: "GIGABYTE GeForce RTX 5060 Ti GAMING OC 8GB",
    descFr: "RTX 5060 Ti 8 Go GDDR7 overclockée d'usine.",
    descAr: "RTX 5060 Ti 8 جيجابايت GDDR7 مكسورة السرعة من المصنع.",
    priceDzd: 129900,
    stock: 8,
    images: ["https://wifidjelfa.com/wp-content/uploads/2026/04/101851018068754435.jpg"],
    featured: false,
    specs: { type: "gpu", tdp: 180, lengthMm: 270, powerConnectors: "1x8-pin" },
  },
  {
    slug: "sapphire-rx-9060-xt",
    categorySlug: "graphics-cards",
    brand: "Sapphire",
    nameFr: "SAPPHIRE PULSE AMD Radeon RX 9060 XT 16GB OC",
    nameAr: "SAPPHIRE PULSE Radeon RX 9060 XT 16GB",
    descFr: "RX 9060 XT 16 Go GDDR6. RDNA 4 milieu de gamme pour le 1080p/1440p.",
    descAr: "RX 9060 XT 16 جيجابايت GDDR6. RDNA 4 متوسطة الفئة لدقة 1080p/1440p.",
    priceDzd: 125900,
    stock: 6,
    images: ["https://wifidjelfa.com/wp-content/uploads/2026/02/101775429664243740.jpg"],
    featured: false,
    specs: { type: "gpu", tdp: 150, lengthMm: 260, powerConnectors: "1x8-pin" },
  },

  // ============ MOTHERBOARDS ============
  {
    slug: "asus-rog-crosshair-x870e-hero",
    categorySlug: "motherboards",
    brand: "ASUS",
    nameFr: "ASUS ROG Crosshair X870E Hero DDR5 ATX",
    nameAr: "ASUS ROG Crosshair X870E Hero",
    descFr: "Carte mère premium AM5 ATX. PCIe 5.0, DDR5, WiFi 7, AI Overclocking.",
    descAr: "لوحة أم AM5 ATX متميزة. PCIe 5.0، DDR5، WiFi 7، كسر سرعة بالذكاء الاصطناعي.",
    priceDzd: 185000,
    stock: 3,
    images: ["https://wifidjelfa.com/wp-content/uploads/2026/02/101775429664243812.jpg"],
    featured: true,
    specs: { type: "motherboard", socket: "AM5", formFactor: "ATX", ramType: "DDR5", ramSlots: 4, maxRam: 256, m2Slots: 5 },
  },
  {
    slug: "asus-x870-ayw-gaming-wifi",
    categorySlug: "motherboards",
    brand: "ASUS",
    nameFr: "ASUS X870 AYW GAMING WIFI DDR5 ATX Blanc",
    nameAr: "ASUS X870 AYW GAMING WIFI أبيض",
    descFr: "Carte mère AM5 ATX blanche avec WiFi, PCIe 5.0 et DDR5.",
    descAr: "لوحة أم AM5 ATX بيضاء مع WiFi، PCIe 5.0 وDDR5.",
    priceDzd: 78900,
    stock: 5,
    images: ["https://wifidjelfa.com/wp-content/uploads/2025/08/101480279780098244.jpg"],
    featured: false,
    specs: { type: "motherboard", socket: "AM5", formFactor: "ATX", ramType: "DDR5", ramSlots: 4, maxRam: 256, m2Slots: 4 },
  },
  {
    slug: "gigabyte-b650e-aorus-stealth-ice",
    categorySlug: "motherboards",
    brand: "GIGABYTE",
    nameFr: "GIGABYTE B650E AORUS Stealth ICE ATX DDR5",
    nameAr: "GIGABYTE B650E AORUS Stealth ICE",
    descFr: "Carte mère AM5 ATX avec connecteurs arrière. DDR5, design blanc épuré.",
    descAr: "لوحة أم AM5 ATX بموصلات خلفية. DDR5، تصميم أبيض أنيق.",
    priceDzd: 77900,
    stock: 4,
    images: ["https://wifidjelfa.com/wp-content/uploads/2026/01/101706070455484499.jpg"],
    featured: false,
    specs: { type: "motherboard", socket: "AM5", formFactor: "ATX", ramType: "DDR5", ramSlots: 4, maxRam: 192, m2Slots: 3 },
  },
  {
    slug: "asus-z890-ayw-gaming-wifi",
    categorySlug: "motherboards",
    brand: "ASUS",
    nameFr: "ASUS Z890 AYW GAMING WIFI DDR5 LGA1851 ATX",
    nameAr: "ASUS Z890 AYW GAMING WIFI",
    descFr: "Carte mère Intel Arrow Lake ATX. Z890, DDR5, PCIe 5.0, WiFi 7.",
    descAr: "لوحة أم Intel Arrow Lake ATX. Z890، DDR5، PCIe 5.0، WiFi 7.",
    priceDzd: 65900,
    stock: 6,
    images: ["https://wifidjelfa.com/wp-content/uploads/2026/02/101752165034360957.jpg"],
    featured: false,
    specs: { type: "motherboard", socket: "LGA1851", formFactor: "ATX", ramType: "DDR5", ramSlots: 4, maxRam: 256, m2Slots: 4 },
  },
  {
    slug: "asus-rog-strix-b760-f-gaming",
    categorySlug: "motherboards",
    brand: "ASUS",
    nameFr: "ASUS ROG STRIX B760-F GAMING WIFI LGA1700 ATX",
    nameAr: "ASUS ROG STRIX B760-F GAMING WIFI",
    descFr: "Carte mère LGA1700 ATX avec WiFi 6E. DDR5, excellent rapport qualité/prix.",
    descAr: "لوحة أم LGA1700 ATX مع WiFi 6E. DDR5، قيمة ممتازة مقابل السعر.",
    priceDzd: 63900,
    stock: 5,
    images: ["https://wifidjelfa.com/wp-content/uploads/2026/02/101775429664243718.jpg"],
    featured: false,
    specs: { type: "motherboard", socket: "LGA1700", formFactor: "ATX", ramType: "DDR5", ramSlots: 4, maxRam: 192, m2Slots: 3 },
  },
  {
    slug: "gigabyte-b860-gaming-x-wifi",
    categorySlug: "motherboards",
    brand: "GIGABYTE",
    nameFr: "GIGABYTE B860 GAMING X WIFI 6E LGA1851",
    nameAr: "GIGABYTE B860 GAMING X WIFI 6E",
    descFr: "Carte mère Intel LGA1851 ATX. B860, DDR5, WiFi 6E, PCIe 5.0.",
    descAr: "لوحة أم Intel LGA1851 ATX. B860، DDR5، WiFi 6E، PCIe 5.0.",
    priceDzd: 61900,
    stock: 8,
    images: ["https://wifidjelfa.com/wp-content/uploads/2025/12/101669562914701483.jpg"],
    featured: false,
    specs: { type: "motherboard", socket: "LGA1851", formFactor: "ATX", ramType: "DDR5", ramSlots: 4, maxRam: 192, m2Slots: 3 },
  },
  {
    slug: "gigabyte-b860m-aorus-elite-wifi",
    categorySlug: "motherboards",
    brand: "GIGABYTE",
    nameFr: "GIGABYTE B860M AORUS ELITE WIFI 6E mATX",
    nameAr: "GIGABYTE B860M AORUS ELITE WIFI 6E",
    descFr: "Carte mère Intel LGA1851 Micro-ATX. B860, DDR5, WiFi 6E, compacte.",
    descAr: "لوحة أم Intel LGA1851 Micro-ATX. B860، DDR5، WiFi 6E، مدمجة.",
    priceDzd: 58900,
    stock: 7,
    images: ["https://wifidjelfa.com/wp-content/uploads/2025/12/101669562914701495.jpg"],
    featured: false,
    specs: { type: "motherboard", socket: "LGA1851", formFactor: "mATX", ramType: "DDR5", ramSlots: 2, maxRam: 96, m2Slots: 2 },
  },
  {
    slug: "asus-prime-b760-plus-ddr5",
    categorySlug: "motherboards",
    brand: "ASUS",
    nameFr: "ASUS Prime B760-PLUS DDR5 LGA1700 ATX",
    nameAr: "ASUS Prime B760-PLUS DDR5",
    descFr: "Carte mère LGA1700 ATX abordable. DDR5, PCIe 5.0, 3x M.2.",
    descAr: "لوحة أم LGA1700 ATX بأسعار معقولة. DDR5، PCIe 5.0، 3x M.2.",
    priceDzd: 39800,
    stock: 10,
    images: ["https://wifidjelfa.com/wp-content/uploads/2025/06/101436158822580244.jpg"],
    featured: false,
    specs: { type: "motherboard", socket: "LGA1700", formFactor: "ATX", ramType: "DDR5", ramSlots: 4, maxRam: 128, m2Slots: 3 },
  },

  // ============ RAM ============
  {
    slug: "dahua-ddr4-32gb-3200",
    categorySlug: "ram",
    brand: "Dahua",
    nameFr: "Dahua DDR4 32GB 3200MHz",
    nameAr: "Dahua DDR4 32GB 3200MHz",
    descFr: "Barrette DDR4 32 Go 3200 MHz pour bureau.",
    descAr: "شريحة ذاكرة DDR4 32 جيجابايت 3200 ميجاهرتز للكمبيوتر المكتبي.",
    priceDzd: 43900,
    stock: 10,
    images: ["https://wifidjelfa.com/wp-content/uploads/woocommerce-placeholder-350x350.png"],
    featured: false,
    specs: { type: "ram", ramType: "DDR4", sizeGb: 32, speed: 3200, sticks: 1 },
  },
  {
    slug: "cusu-rgb-ddr4-8gb-3600",
    categorySlug: "ram",
    brand: "CUSU",
    nameFr: "CUSU RGB DDR4 8GB 3600MHz CL16",
    nameAr: "CUSU RGB DDR4 8GB 3600MHz",
    descFr: "RAM DDR4 8 Go 3600 MHz avec éclairage RGB.",
    descAr: "ذاكرة DDR4 8 جيجابايت 3600 ميجاهرتز مع إضاءة RGB.",
    priceDzd: 16900,
    stock: 20,
    images: ["https://wifidjelfa.com/wp-content/uploads/2026/03/101825006958280813.jpg"],
    featured: false,
    specs: { type: "ram", ramType: "DDR4", sizeGb: 8, speed: 3600, sticks: 1 },
  },
  {
    slug: "corsair-vengeance-lpx-8gb-3200",
    categorySlug: "ram",
    brand: "Corsair",
    nameFr: "Corsair Vengeance LPX 8GB DDR4 3200MHz",
    nameAr: "Corsair Vengeance LPX 8GB DDR4",
    descFr: "RAM DDR4 8 Go 3200 MHz CL16, profil bas.",
    descAr: "ذاكرة DDR4 8 جيجابايت 3200 ميجاهرتز CL16، منخفضة الارتفاع.",
    priceDzd: 15500,
    stock: 25,
    images: ["https://wifidjelfa.com/wp-content/uploads/2026/03/101833968206217250.jpg"],
    featured: false,
    specs: { type: "ram", ramType: "DDR4", sizeGb: 8, speed: 3200, sticks: 1 },
  },
  {
    slug: "adata-premier-8gb-3200",
    categorySlug: "ram",
    brand: "ADATA",
    nameFr: "ADATA Premier 8GB DDR4 3200MHz",
    nameAr: "ADATA Premier 8GB DDR4",
    descFr: "RAM DDR4 8 Go 3200 MHz CL19, fiable et abordable.",
    descAr: "ذاكرة DDR4 8 جيجابايت 3200 ميجاهرتز CL19، موثوقة وبأسعار معقولة.",
    priceDzd: 14500,
    stock: 30,
    images: ["https://wifidjelfa.com/wp-content/uploads/2026/03/101833968206217249.jpg"],
    featured: false,
    specs: { type: "ram", ramType: "DDR4", sizeGb: 8, speed: 3200, sticks: 1 },
  },
  {
    slug: "adata-xpg-lancer-ddr5-16gb-6400",
    categorySlug: "ram",
    brand: "ADATA",
    nameFr: "ADATA XPG Lancer DDR5 RGB 16GB 6400MHz",
    nameAr: "ADATA XPG Lancer DDR5 RGB 16GB",
    descFr: "RAM DDR5 16 Go 6400 MHz avec RGB. CL32, haute performance.",
    descAr: "ذاكرة DDR5 16 جيجابايت 6400 ميجاهرتز مع RGB. CL32، أداء عالي.",
    priceDzd: 47900,
    stock: 6,
    images: ["https://wifidjelfa.com/wp-content/uploads/2026/03/101797479304921097.jpg"],
    featured: true,
    specs: { type: "ram", ramType: "DDR5", sizeGb: 16, speed: 6400, sticks: 1 },
  },

  // ============ STORAGE ============
  {
    slug: "samsung-990-pro-4tb",
    categorySlug: "ssds",
    brand: "Samsung",
    nameFr: "Samsung 990 PRO M.2 NVMe 4TB PCIe 4.0",
    nameAr: "Samsung 990 PRO 4TB NVMe",
    descFr: "SSD NVMe Gen4 haut de gamme. 4 To, jusqu'à 7450 Mo/s.",
    descAr: "SSD NVMe Gen4 عالي الأداء. 4 تيرابايت، حتى 7450 ميجابايت/ثانية.",
    priceDzd: 99000,
    stock: 4,
    images: ["https://wifidjelfa.com/wp-content/uploads/2026/03/101800349114826841.jpg"],
    featured: true,
    specs: { type: "storage", capacity: "4TB", interface: "NVMe PCIe 4.0" },
  },
  {
    slug: "samsung-990-evo-plus-2tb",
    categorySlug: "ssds",
    brand: "Samsung",
    nameFr: "Samsung 990 EVO Plus M.2 NVMe 2TB",
    nameAr: "Samsung 990 EVO Plus 2TB",
    descFr: "SSD NVMe Gen4 2 To. 7250/6300 Mo/s, excellent rapport qualité/prix.",
    descAr: "SSD NVMe Gen4 بسعة 2 تيرابايت. 7250/6300 ميجابايت/ثانية، قيمة ممتازة.",
    priceDzd: 52900,
    stock: 8,
    images: ["https://wifidjelfa.com/wp-content/uploads/2026/03/101800349114826842.jpg"],
    featured: false,
    specs: { type: "storage", capacity: "2TB", interface: "NVMe PCIe 4.0" },
  },
  {
    slug: "samsung-9100-pro-1tb",
    categorySlug: "ssds",
    brand: "Samsung",
    nameFr: "Samsung 9100 PRO 1TB M.2 PCIe 5.0 NVMe 2.0",
    nameAr: "Samsung 9100 PRO 1TB PCIe 5.0",
    descFr: "SSD PCIe Gen5 ultra-rapide. 1 To, dernière génération Samsung.",
    descAr: "SSD PCIe Gen5 فائق السرعة. 1 تيرابايت، أحدث جيل من Samsung.",
    priceDzd: 44900,
    stock: 5,
    images: ["https://wifidjelfa.com/wp-content/uploads/2026/03/101800349114826843.jpg"],
    featured: false,
    specs: { type: "storage", capacity: "1TB", interface: "NVMe PCIe 5.0" },
  },
  {
    slug: "samsung-990-evo-plus-1tb",
    categorySlug: "ssds",
    brand: "Samsung",
    nameFr: "Samsung 990 EVO Plus M.2 NVMe 1TB",
    nameAr: "Samsung 990 EVO Plus 1TB",
    descFr: "SSD NVMe Gen4 1 To. Rapide et fiable pour le système et les jeux.",
    descAr: "SSD NVMe Gen4 بسعة 1 تيرابايت. سريع وموثوق للنظام والألعاب.",
    priceDzd: 36500,
    stock: 12,
    images: ["https://wifidjelfa.com/wp-content/uploads/2026/03/101800349114826844.jpg"],
    featured: false,
    specs: { type: "storage", capacity: "1TB", interface: "NVMe PCIe 4.0" },
  },
  {
    slug: "hiksemi-wave-1tb-nvme",
    categorySlug: "ssds",
    brand: "HIKsemi",
    nameFr: "HIKsemi WAVE 1TB NVMe M.2 PCIe 3.0",
    nameAr: "HIKsemi WAVE 1TB NVMe",
    descFr: "SSD NVMe Gen3 1 To. Abordable et fiable.",
    descAr: "SSD NVMe Gen3 بسعة 1 تيرابايت. بأسعار معقولة وموثوق.",
    priceDzd: 27500,
    stock: 15,
    images: ["https://wifidjelfa.com/wp-content/uploads/2026/02/101775429664243761.jpg"],
    featured: false,
    specs: { type: "storage", capacity: "1TB", interface: "NVMe PCIe 3.0" },
  },
  {
    slug: "hiksemi-wave-512gb-nvme",
    categorySlug: "ssds",
    brand: "HIKsemi",
    nameFr: "HIKsemi WAVE 512GB NVMe M.2 PCIe 3.0",
    nameAr: "HIKsemi WAVE 512GB NVMe",
    descFr: "SSD NVMe Gen3 512 Go. Jusqu'à 2500 Mo/s.",
    descAr: "SSD NVMe Gen3 بسعة 512 جيجابايت. حتى 2500 ميجابايت/ثانية.",
    priceDzd: 20900,
    stock: 20,
    images: ["https://wifidjelfa.com/wp-content/uploads/2026/02/101775429664243775.jpg"],
    featured: false,
    specs: { type: "storage", capacity: "512GB", interface: "NVMe PCIe 3.0" },
  },
  {
    slug: "adata-su650-512gb-sata",
    categorySlug: "ssds",
    brand: "ADATA",
    nameFr: "ADATA SU650 512GB SATA III 2.5\"",
    nameAr: "ADATA SU650 512GB SATA",
    descFr: "SSD SATA 512 Go. Idéal pour mise à niveau abordable.",
    descAr: "SSD SATA بسعة 512 جيجابايت. مثالي للترقية بسعر مناسب.",
    priceDzd: 17500,
    stock: 18,
    images: ["https://wifidjelfa.com/wp-content/uploads/2026/02/101775429664243773.jpg"],
    featured: false,
    specs: { type: "storage", capacity: "512GB", interface: "SATA III" },
  },

  // ============ POWER SUPPLIES ============
  {
    slug: "cooler-master-mwe-850w-gold",
    categorySlug: "power-supplies",
    brand: "Cooler Master",
    nameFr: "Cooler Master MWE 850W Gold V2 Full Modular",
    nameAr: "Cooler Master MWE 850W Gold V2",
    descFr: "Alimentation 850W 80+ Gold entièrement modulaire. Idéale pour les configurations haut de gamme.",
    descAr: "مزود طاقة 850 واط 80+ Gold معياري بالكامل. مثالي للتكوينات عالية الأداء.",
    priceDzd: 23900,
    stock: 10,
    images: ["https://wifidjelfa.com/wp-content/uploads/2025/06/101415881241788470.jpg"],
    featured: true,
    specs: { type: "psu", wattage: 850, formFactor: "ATX", rating: "80+ Gold" },
  },
  {
    slug: "cooler-master-mwe-750w-gold",
    categorySlug: "power-supplies",
    brand: "Cooler Master",
    nameFr: "Cooler Master MWE 750W Gold V2 Full Modular",
    nameAr: "Cooler Master MWE 750W Gold V2",
    descFr: "Alimentation 750W 80+ Gold entièrement modulaire.",
    descAr: "مزود طاقة 750 واط 80+ Gold معياري بالكامل.",
    priceDzd: 21900,
    stock: 12,
    images: ["https://wifidjelfa.com/wp-content/uploads/2025/01/101203220130431054.jpg"],
    featured: false,
    specs: { type: "psu", wattage: 750, formFactor: "ATX", rating: "80+ Gold" },
  },
  {
    slug: "acer-1000w-80-gold",
    categorySlug: "power-supplies",
    brand: "Acer",
    nameFr: "Acer AC1000 1000W 80+ Gold Full Modular",
    nameAr: "Acer AC1000 1000W 80+ Gold",
    descFr: "Alimentation 1000W 80+ Gold modulaire pour les builds les plus gourmands.",
    descAr: "مزود طاقة 1000 واط 80+ Gold معياري للتكوينات الأكثر استهلاكاً.",
    priceDzd: 19900,
    stock: 6,
    images: ["https://wifidjelfa.com/wp-content/uploads/2025/05/101370403896688645.png"],
    featured: false,
    specs: { type: "psu", wattage: 1000, formFactor: "ATX", rating: "80+ Gold" },
  },
  {
    slug: "thermaltake-750w-smart-bx3",
    categorySlug: "power-supplies",
    brand: "Thermaltake",
    nameFr: "Thermaltake Smart BX3 750W 80+ Bronze",
    nameAr: "Thermaltake Smart BX3 750W",
    descFr: "Alimentation 750W 80+ Bronze. Bon rapport qualité/prix.",
    descAr: "مزود طاقة 750 واط 80+ Bronze. قيمة جيدة مقابل السعر.",
    priceDzd: 15700,
    stock: 14,
    images: ["https://wifidjelfa.com/wp-content/uploads/2026/03/101791771880587278.jpg"],
    featured: false,
    specs: { type: "psu", wattage: 750, formFactor: "ATX", rating: "80+ Bronze" },
  },
  {
    slug: "cooler-master-v3-550w-bronze",
    categorySlug: "power-supplies",
    brand: "Cooler Master",
    nameFr: "Cooler Master V3 Bronze 550W",
    nameAr: "Cooler Master V3 Bronze 550W",
    descFr: "Alimentation 550W 80+ Bronze. Parfaite pour les configs milieu de gamme.",
    descAr: "مزود طاقة 550 واط 80+ Bronze. مثالي للتكوينات المتوسطة.",
    priceDzd: 11900,
    stock: 16,
    images: ["https://wifidjelfa.com/wp-content/uploads/2025/10/101582932484816976.jpg"],
    featured: false,
    specs: { type: "psu", wattage: 550, formFactor: "ATX", rating: "80+ Bronze" },
  },
  {
    slug: "fsp-hyper-k-700w",
    categorySlug: "power-supplies",
    brand: "FSP",
    nameFr: "FSP HYPER K 700W 80 PLUS",
    nameAr: "FSP HYPER K 700W",
    descFr: "Alimentation 700W 80 PLUS certifiée.",
    descAr: "مزود طاقة 700 واط 80 PLUS معتمد.",
    priceDzd: 11400,
    stock: 15,
    images: ["https://wifidjelfa.com/wp-content/uploads/2025/11/101643729927929890.jpg"],
    featured: false,
    specs: { type: "psu", wattage: 700, formFactor: "ATX", rating: "80+" },
  },
  {
    slug: "gigabyte-gp-p550b-550w",
    categorySlug: "power-supplies",
    brand: "GIGABYTE",
    nameFr: "GIGABYTE GP-P550B 550W 80+ Bronze",
    nameAr: "GIGABYTE GP-P550B 550W",
    descFr: "Alimentation 550W 80+ Bronze fiable.",
    descAr: "مزود طاقة 550 واط 80+ Bronze موثوق.",
    priceDzd: 10500,
    stock: 18,
    images: ["https://wifidjelfa.com/wp-content/uploads/2026/01/101706070455484532.jpg"],
    featured: false,
    specs: { type: "psu", wattage: 550, formFactor: "ATX", rating: "80+ Bronze" },
  },

  // ============ CASES ============
  {
    slug: "nzxt-h9-flow-white",
    categorySlug: "cases",
    brand: "NZXT",
    nameFr: "NZXT H9 Flow Mid Tower ATX Blanc",
    nameAr: "NZXT H9 Flow Mid Tower أبيض",
    descFr: "Boîtier ATX mid-tower premium avec flux d'air optimisé et panneau verre trempé.",
    descAr: "صندوق ATX mid-tower متميز مع تدفق هواء محسّن ولوحة زجاج مقسّى.",
    priceDzd: 49900,
    stock: 4,
    images: ["https://wifidjelfa.com/wp-content/uploads/2026/02/101775429664243735.jpg"],
    featured: true,
    specs: { type: "case", supportedFormFactors: ["ATX", "mATX", "ITX"], maxGpuLengthMm: 435, maxCoolerHeightMm: 165 },
  },
  {
    slug: "mars-mc-lcd-mini-tower",
    categorySlug: "cases",
    brand: "MARS",
    nameFr: "MARS MC-LCD Mini Tower avec écran LCD",
    nameAr: "MARS MC-LCD Mini Tower مع شاشة LCD",
    descFr: "Boîtier mini tour avec écran LCD intégré en façade.",
    descAr: "صندوق ميني تاور مع شاشة LCD مدمجة في الواجهة.",
    priceDzd: 32900,
    stock: 5,
    images: ["https://wifidjelfa.com/wp-content/uploads/2025/07/101457911053549574.jpg"],
    featured: false,
    specs: { type: "case", supportedFormFactors: ["mATX", "ITX"], maxGpuLengthMm: 350, maxCoolerHeightMm: 160 },
  },
  {
    slug: "mars-mc-ultra-e-atx-white",
    categorySlug: "cases",
    brand: "MARS",
    nameFr: "MARS GAMING MC-ULTRA E-ATX Premium Blanc",
    nameAr: "MARS GAMING MC-ULTRA E-ATX أبيض",
    descFr: "Boîtier E-ATX XXL premium blanc. Support GPU jusqu'à 400mm.",
    descAr: "صندوق E-ATX XXL أبيض متميز. دعم GPU حتى 400 مم.",
    priceDzd: 26500,
    stock: 6,
    images: ["https://wifidjelfa.com/wp-content/uploads/2024/06/100895552111116358.jpg"],
    featured: false,
    specs: { type: "case", supportedFormFactors: ["E-ATX", "ATX", "mATX", "ITX"], maxGpuLengthMm: 400, maxCoolerHeightMm: 175 },
  },
  {
    slug: "magma-atx-v5-argb-white",
    categorySlug: "cases",
    brand: "MAGMA",
    nameFr: "MAGMA ATX V5 ARGB Sync Blanc",
    nameAr: "MAGMA ATX V5 ARGB أبيض",
    descFr: "Boîtier ATX avec ventilateurs ARGB synchronisés. Design blanc moderne.",
    descAr: "صندوق ATX مع مراوح ARGB متزامنة. تصميم أبيض عصري.",
    priceDzd: 23900,
    stock: 8,
    images: ["https://wifidjelfa.com/wp-content/uploads/2025/08/101480279780098234.jpg"],
    featured: false,
    specs: { type: "case", supportedFormFactors: ["ATX", "mATX", "ITX"], maxGpuLengthMm: 380, maxCoolerHeightMm: 165 },
  },
  {
    slug: "deepcool-cg580-white",
    categorySlug: "cases",
    brand: "DeepCool",
    nameFr: "DeepCool CG580 Blanc",
    nameAr: "DeepCool CG580 أبيض",
    descFr: "Boîtier ATX avec mesh frontal pour un flux d'air optimal.",
    descAr: "صندوق ATX مع شبكة أمامية لتدفق هواء مثالي.",
    priceDzd: 14900,
    stock: 10,
    images: ["https://wifidjelfa.com/wp-content/uploads/2026/02/101775429664243804.jpg"],
    featured: false,
    specs: { type: "case", supportedFormFactors: ["ATX", "mATX", "ITX"], maxGpuLengthMm: 380, maxCoolerHeightMm: 165 },
  },
  {
    slug: "cougar-archon-2-mesh-rgb",
    categorySlug: "cases",
    brand: "COUGAR",
    nameFr: "COUGAR Archon 2 Mesh RGB Mid Tower",
    nameAr: "COUGAR Archon 2 Mesh RGB",
    descFr: "Boîtier mid-tower avec mesh et RGB. Refroidissement haute performance.",
    descAr: "صندوق mid-tower مع شبكة وRGB. تبريد عالي الأداء.",
    priceDzd: 15900,
    stock: 12,
    images: ["https://wifidjelfa.com/wp-content/uploads/2024/03/100734162591285630.jpg"],
    featured: false,
    specs: { type: "case", supportedFormFactors: ["ATX", "mATX", "ITX"], maxGpuLengthMm: 370, maxCoolerHeightMm: 165 },
  },

  // ============ COOLING ============
  {
    slug: "msi-mpg-coreliquid-d360",
    categorySlug: "cpu-cooling",
    brand: "MSI",
    nameFr: "MSI MPG CoreLiquid D360 ARGB avec écran IPS 2.4\"",
    nameAr: "MSI MPG CoreLiquid D360 ARGB مع شاشة IPS",
    descFr: "Kit watercooling 360mm ARGB avec écran IPS 2.4 pouces. Compatible Intel/AMD.",
    descAr: "مجموعة تبريد مائي 360 مم ARGB مع شاشة IPS 2.4 بوصة. متوافق مع Intel/AMD.",
    priceDzd: 49000,
    stock: 4,
    images: ["https://wifidjelfa.com/wp-content/uploads/2025/08/101502848809828427.jpg"],
    featured: true,
    specs: { type: "cooler", socket: ["LGA1700", "LGA1851", "AM5", "AM4"], heightMm: 27, tdpSupport: 350 },
  },
  {
    slug: "nzxt-kraken-240-rgb-white",
    categorySlug: "cpu-cooling",
    brand: "NZXT",
    nameFr: "NZXT Kraken 240 RGB Blanc",
    nameAr: "NZXT Kraken 240 RGB أبيض",
    descFr: "AIO 240mm avec éclairage RGB. Compatible LGA1700/1851/AM5.",
    descAr: "AIO 240 مم مع إضاءة RGB. متوافق مع LGA1700/1851/AM5.",
    priceDzd: 38900,
    stock: 5,
    images: ["https://wifidjelfa.com/wp-content/uploads/2025/12/101669562914701382.jpg"],
    featured: false,
    specs: { type: "cooler", socket: ["LGA1700", "LGA1851", "AM5"], heightMm: 27, tdpSupport: 250 },
  },
  {
    slug: "deepcool-mystique-240-argb",
    categorySlug: "cpu-cooling",
    brand: "DeepCool",
    nameFr: "DeepCool Mystique 240 ARGB",
    nameAr: "DeepCool Mystique 240 ARGB",
    descFr: "AIO 240mm avec écran LCD et ARGB.",
    descAr: "AIO 240 مم مع شاشة LCD وARGB.",
    priceDzd: 36900,
    stock: 6,
    images: ["https://wifidjelfa.com/wp-content/uploads/2025/07/101452094241767482.jpg"],
    featured: false,
    specs: { type: "cooler", socket: ["LGA1700", "LGA1851", "AM5", "AM4"], heightMm: 27, tdpSupport: 280 },
  },
  {
    slug: "deepcool-lt240-argb-white",
    categorySlug: "cpu-cooling",
    brand: "DeepCool",
    nameFr: "DeepCool LT240 ARGB Blanc",
    nameAr: "DeepCool LT240 ARGB أبيض",
    descFr: "AIO 240mm ARGB blanc. Excellent rapport qualité/prix.",
    descAr: "AIO 240 مم ARGB أبيض. قيمة ممتازة مقابل السعر.",
    priceDzd: 32900,
    stock: 8,
    images: ["https://wifidjelfa.com/wp-content/uploads/2025/03/101298626269020165.jpg"],
    featured: false,
    specs: { type: "cooler", socket: ["LGA1700", "LGA1851", "AM5", "AM4"], heightMm: 27, tdpSupport: 250 },
  },
  {
    slug: "deepcool-assassin-iv-white",
    categorySlug: "cpu-cooling",
    brand: "DeepCool",
    nameFr: "DeepCool Assassin IV Blanc - Ventirad",
    nameAr: "DeepCool Assassin IV أبيض - مبرد هوائي",
    descFr: "Ventirad haut de gamme double tour. TDP 280W, silencieux.",
    descAr: "مبرد هوائي عالي الأداء بصفين. TDP 280W، هادئ.",
    priceDzd: 20900,
    stock: 7,
    images: ["https://wifidjelfa.com/wp-content/uploads/2025/11/101646735230631970.jpg"],
    featured: false,
    specs: { type: "cooler", socket: ["LGA1700", "LGA1851", "AM5", "AM4"], heightMm: 164, tdpSupport: 280 },
  },
  {
    slug: "thermalright-core-vision-360-white",
    categorySlug: "cpu-cooling",
    brand: "Thermalright",
    nameFr: "Thermalright Core Vision 360 ARGB Blanc",
    nameAr: "Thermalright Core Vision 360 ARGB أبيض",
    descFr: "AIO 360mm ARGB blanc avec écran LCD. Compatible toutes plateformes.",
    descAr: "AIO 360 مم ARGB أبيض مع شاشة LCD. متوافق مع جميع المنصات.",
    priceDzd: 27700,
    stock: 6,
    images: ["https://wifidjelfa.com/wp-content/uploads/2026/01/101706070455484466.jpg"],
    featured: false,
    specs: { type: "cooler", socket: ["LGA1700", "LGA1851", "AM5", "AM4"], heightMm: 27, tdpSupport: 300 },
  },

  // ============ KEYBOARDS ============
  {
    slug: "attack-shark-x820-ultra-mechanical-keyboard",
    categorySlug: "keyboards",
    brand: "Attack Shark",
    nameFr: "Attack Shark X820 Ultra Tri-mode Gasket Mécanique",
    nameAr: "أتاك شارك X820 ألترا كيبورد ميكانيكي",
    descFr: "Clavier mécanique gasket tri-mode (filaire, 2.4G, Bluetooth). Construction premium, RGB, hot-swap.",
    descAr: "كيبورد ميكانيكي gasket ثلاثي الوضع (سلكي، 2.4G، بلوتوث). بناء متميز، RGB، تبديل سريع.",
    priceDzd: 19900,
    stock: 5,
    images: ["https://wifidjelfa.com/wp-content/uploads/2026/01/101720483912744995.jpg"],
    featured: true,
    specs: { type: "accessory", subtype: "keyboard" },
  },
  {
    slug: "attack-shark-k85-rapid-trigger",
    categorySlug: "keyboards",
    brand: "Attack Shark",
    nameFr: "Attack Shark K85 Rapid Trigger Magnetic Switch",
    nameAr: "أتاك شارك K85 رابيد تريغر مفتاح مغناطيسي",
    descFr: "Clavier gaming avec switches magnétiques Rapid Trigger. Réponse ultra-rapide pour le jeu compétitif.",
    descAr: "كيبورد ألعاب مع مفاتيح مغناطيسية Rapid Trigger. استجابة فائقة السرعة للألعاب التنافسية.",
    priceDzd: 19500,
    stock: 4,
    images: ["https://wifidjelfa.com/wp-content/uploads/2025/11/101639147986354192-350x350.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "keyboard" },
  },
  {
    slug: "aula-f108-pro-tri-mode-mechanical",
    categorySlug: "keyboards",
    brand: "AULA",
    nameFr: "AULA F108 PRO Tri-mode Mécanique avec Écran et Molette",
    nameAr: "أولا F108 PRO كيبورد ميكانيكي مع شاشة ومقبض",
    descFr: "Clavier mécanique full-size tri-mode avec écran LCD et molette de volume. RGB, hot-swap.",
    descAr: "كيبورد ميكانيكي كامل الحجم ثلاثي الوضع مع شاشة LCD ومقبض صوت. RGB، تبديل سريع.",
    priceDzd: 18900,
    stock: 6,
    images: ["https://wifidjelfa.com/wp-content/uploads/2026/03/101825006958280782.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "keyboard" },
  },
  {
    slug: "attack-shark-x98-pro-wireless",
    categorySlug: "keyboards",
    brand: "Attack Shark",
    nameFr: "Attack Shark X98 PRO Wireless RGB Hot-Swap",
    nameAr: "أتاك شارك X98 PRO لاسلكي RGB",
    descFr: "Clavier gaming sans fil avec RGB et switches hot-swap. Design Cheese White BlueBerry.",
    descAr: "كيبورد ألعاب لاسلكي مع RGB ومفاتيح قابلة للتبديل السريع.",
    priceDzd: 18500,
    stock: 5,
    images: ["https://wifidjelfa.com/wp-content/uploads/2025/11/101639147986354189.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "keyboard" },
  },
  {
    slug: "aula-hero-68-he-magnetic-8k",
    categorySlug: "keyboards",
    brand: "AULA",
    nameFr: "AULA Hero 68 HE Magnétique 8K Polling",
    nameAr: "أولا هيرو 68 HE مغناطيسي 8K",
    descFr: "Clavier gaming compact 68 touches avec switches magnétiques et polling rate 8K Hz.",
    descAr: "كيبورد ألعاب مدمج 68 مفتاح مع مفاتيح مغناطيسية ومعدل استطلاع 8K هرتز.",
    priceDzd: 17900,
    stock: 4,
    images: ["https://wifidjelfa.com/wp-content/uploads/2025/11/101640524825362463.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "keyboard" },
  },
  {
    slug: "aula-f87-pro-tri-mode-gasket",
    categorySlug: "keyboards",
    brand: "AULA",
    nameFr: "AULA F87 PRO Tri-mode Gasket Mécanique 8000mAh",
    nameAr: "أولا F87 PRO ميكانيكي ثلاثي الوضع 8000mAh",
    descFr: "Clavier mécanique gasket 87 touches, batterie 8000 mAh, tri-mode, switches magnétiques.",
    descAr: "كيبورد ميكانيكي gasket 87 مفتاح، بطارية 8000 مللي أمبير، ثلاثي الوضع.",
    priceDzd: 16900,
    stock: 6,
    images: ["https://wifidjelfa.com/wp-content/uploads/2026/03/101825006958280819.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "keyboard" },
  },
  {
    slug: "attack-shark-m87pro-wireless-mechanical",
    categorySlug: "keyboards",
    brand: "Attack Shark",
    nameFr: "Attack Shark M87PRO Wireless Mécanique PBT",
    nameAr: "أتاك شارك M87PRO لاسلكي ميكانيكي PBT",
    descFr: "Clavier mécanique sans fil avec keycaps PBT imprimés sur le côté. Design MoonLit Night.",
    descAr: "كيبورد ميكانيكي لاسلكي مع أغطية مفاتيح PBT. تصميم MoonLit Night.",
    priceDzd: 16500,
    stock: 5,
    images: ["https://wifidjelfa.com/wp-content/uploads/2025/11/101639147986354183.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "keyboard" },
  },
  {
    slug: "aula-win68-he-max-magnetic",
    categorySlug: "keyboards",
    brand: "AULA",
    nameFr: "AULA WIN68 HE Max Magnétique Rouge/Noir",
    nameAr: "أولا WIN68 HE Max مغناطيسي أحمر/أسود",
    descFr: "Clavier gaming compact 68 touches avec switches magnétiques. Design rouge et noir.",
    descAr: "كيبورد ألعاب مدمج 68 مفتاح مع مفاتيح مغناطيسية. تصميم أحمر وأسود.",
    priceDzd: 16500,
    stock: 4,
    images: ["https://wifidjelfa.com/wp-content/uploads/2025/11/101652165948342300.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "keyboard" },
  },
  {
    slug: "aula-f108-tri-mode-mechanical",
    categorySlug: "keyboards",
    brand: "AULA",
    nameFr: "AULA F108 Tri-mode Full Size Mécanique",
    nameAr: "أولا F108 ميكانيكي كامل الحجم ثلاثي الوضع",
    descFr: "Clavier mécanique full-size tri-mode. RGB, hot-swap, connectivité polyvalente.",
    descAr: "كيبورد ميكانيكي كامل الحجم ثلاثي الوضع. RGB، تبديل سريع.",
    priceDzd: 15900,
    stock: 6,
    images: ["https://wifidjelfa.com/wp-content/uploads/2025/11/101639147986354195.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "keyboard" },
  },
  {
    slug: "attack-shark-x68-he-magnetic-white",
    categorySlug: "keyboards",
    brand: "Attack Shark",
    nameFr: "Attack Shark X68 HE Magnétique Blanc",
    nameAr: "أتاك شارك X68 HE مغناطيسي أبيض",
    descFr: "Clavier gaming compact 68 touches avec switches magnétiques. Design blanc contour line.",
    descAr: "كيبورد ألعاب مدمج 68 مفتاح مع مفاتيح مغناطيسية. تصميم أبيض.",
    priceDzd: 15900,
    stock: 5,
    images: ["https://wifidjelfa.com/wp-content/uploads/2026/04/101855071024709657.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "keyboard" },
  },
  {
    slug: "ajazz-ak680-max-8k-magnetic",
    categorySlug: "keyboards",
    brand: "AJAZZ",
    nameFr: "AJAZZ AK680 MAX 8K Magnétique USB-C",
    nameAr: "أجاز AK680 MAX 8K مغناطيسي USB-C",
    descFr: "Clavier mécanique filaire 8K USB-C avec switches magnétiques. Design Topo Graphique blanc.",
    descAr: "كيبورد ميكانيكي سلكي 8K USB-C مع مفاتيح مغناطيسية.",
    priceDzd: 15900,
    stock: 4,
    images: ["https://wifidjelfa.com/wp-content/uploads/2025/08/101502848809828452.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "keyboard" },
  },
  {
    slug: "aula-win60-he-pro-8k-magnetic",
    categorySlug: "keyboards",
    brand: "AULA",
    nameFr: "AULA WIN60 HE PRO 8K Magnétique",
    nameAr: "أولا WIN60 HE PRO 8K مغناطيسي",
    descFr: "Clavier gaming compact 60% avec switches magnétiques et polling rate 8K Hz.",
    descAr: "كيبورد ألعاب مدمج 60% مع مفاتيح مغناطيسية ومعدل استطلاع 8K هرتز.",
    priceDzd: 14500,
    stock: 6,
    images: ["https://wifidjelfa.com/wp-content/uploads/2025/12/101669562914701635.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "keyboard" },
  },

  // ============ MICE ============
  {
    slug: "logitech-g-pro-x-superlight-2",
    categorySlug: "mice",
    brand: "Logitech",
    nameFr: "Logitech G Pro X Superlight 2 Sans Fil",
    nameAr: "لوجيتك G Pro X Superlight 2 لاسلكي",
    descFr: "Souris gaming sans fil ultra-légère. Capteur HERO 2, autonomie 95h, 60g.",
    descAr: "فأرة ألعاب لاسلكية خفيفة الوزن. مستشعر HERO 2، بطارية 95 ساعة، 60 غرام.",
    priceDzd: 32900,
    stock: 3,
    images: ["https://wifidjelfa.com/wp-content/uploads/2026/03/101800349114826789.jpg"],
    featured: true,
    specs: { type: "accessory", subtype: "mouse" },
  },
  {
    slug: "ajazz-aj179-apex-8k-paw3950",
    categorySlug: "mice",
    brand: "AJAZZ",
    nameFr: "AJAZZ AJ179 APEX 8K PAW3950 Sans Fil Bleu",
    nameAr: "أجاز AJ179 APEX 8K PAW3950 لاسلكي أزرق",
    descFr: "Souris gaming sans fil avec capteur PAW3950 et polling rate 8K Hz. Design bleu.",
    descAr: "فأرة ألعاب لاسلكية مع مستشعر PAW3950 ومعدل استطلاع 8K هرتز.",
    priceDzd: 17500,
    stock: 4,
    images: ["https://wifidjelfa.com/wp-content/uploads/2026/03/101833968206217233.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "mouse" },
  },
  {
    slug: "galax-gaming-mouse-ace-m2-white",
    categorySlug: "mice",
    brand: "GALAX",
    nameFr: "GALAX Gaming Mouse ACE M2 Blanc",
    nameAr: "جالاكس فأرة ألعاب ACE M2 أبيض",
    descFr: "Souris gaming haute performance GALAX ACE M2. Design blanc élégant.",
    descAr: "فأرة ألعاب عالية الأداء GALAX ACE M2. تصميم أبيض أنيق.",
    priceDzd: 16900,
    stock: 5,
    images: ["https://wifidjelfa.com/wp-content/uploads/2024/10/101085375002312754.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "mouse" },
  },
  {
    slug: "galax-gaming-mouse-ace-m2-black",
    categorySlug: "mice",
    brand: "GALAX",
    nameFr: "GALAX Gaming Mouse ACE M2 Noir",
    nameAr: "جالاكس فأرة ألعاب ACE M2 أسود",
    descFr: "Souris gaming haute performance GALAX ACE M2. Design noir.",
    descAr: "فأرة ألعاب عالية الأداء GALAX ACE M2. تصميم أسود.",
    priceDzd: 16900,
    stock: 5,
    images: ["https://wifidjelfa.com/wp-content/uploads/2024/10/101085375002312753.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "mouse" },
  },
  {
    slug: "glorious-model-i-matte-white",
    categorySlug: "mice",
    brand: "Glorious",
    nameFr: "Glorious Model I Blanc Mat 19000 DPI",
    nameAr: "غلوريوس Model I أبيض مطفي 19000 DPI",
    descFr: "Souris gaming filaire ergonomique. Capteur 19000 DPI, 9 boutons, RGB.",
    descAr: "فأرة ألعاب سلكية مريحة. مستشعر 19000 DPI، 9 أزرار، RGB.",
    priceDzd: 15900,
    stock: 4,
    images: ["https://wifidjelfa.com/wp-content/uploads/2024/03/100734162591285636.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "mouse" },
  },
  {
    slug: "attack-shark-x3pro-white-8k",
    categorySlug: "mice",
    brand: "Attack Shark",
    nameFr: "Attack Shark X3 PRO Blanc 8K PAW3395 59g",
    nameAr: "أتاك شارك X3 PRO أبيض 8K PAW3395 59غ",
    descFr: "Souris gaming tri-mode 4K/8K Hz, 59g ultra-légère, capteur PAW3395, 26000 DPI, 200h d'autonomie.",
    descAr: "فأرة ألعاب ثلاثية الوضع 4K/8K هرتز، 59 غرام خفيفة، مستشعر PAW3395، 26000 DPI.",
    priceDzd: 11900,
    stock: 6,
    images: ["https://wifidjelfa.com/wp-content/uploads/2026/02/101775429664243745.jpg"],
    featured: true,
    specs: { type: "accessory", subtype: "mouse" },
  },
  {
    slug: "attack-shark-x3pro-black-8k",
    categorySlug: "mice",
    brand: "Attack Shark",
    nameFr: "Attack Shark X3 PRO Noir 8K PAW3395 59g",
    nameAr: "أتاك شارك X3 PRO أسود 8K PAW3395 59غ",
    descFr: "Souris gaming tri-mode 4K/8K Hz, 59g ultra-légère, capteur PAW3395, 26000 DPI, 200h d'autonomie.",
    descAr: "فأرة ألعاب ثلاثية الوضع 4K/8K هرتز، 59 غرام خفيفة، مستشعر PAW3395، 26000 DPI.",
    priceDzd: 11900,
    stock: 6,
    images: ["https://wifidjelfa.com/wp-content/uploads/2026/02/101775429664243744.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "mouse" },
  },
  {
    slug: "ajazz-aj179p-paw3395-wireless",
    categorySlug: "mice",
    brand: "AJAZZ",
    nameFr: "AJAZZ AJ179P PAW3395 Sans Fil",
    nameAr: "أجاز AJ179P PAW3395 لاسلكي",
    descFr: "Souris gaming sans fil avec capteur PAW3395. Légère et précise.",
    descAr: "فأرة ألعاب لاسلكية مع مستشعر PAW3395. خفيفة ودقيقة.",
    priceDzd: 9500,
    stock: 5,
    images: ["https://wifidjelfa.com/wp-content/uploads/2025/05/101375477343584457.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "mouse" },
  },
  {
    slug: "attack-shark-x6-paw3395-trimode",
    categorySlug: "mice",
    brand: "Attack Shark",
    nameFr: "Attack Shark X6 PAW3395 26000 DPI Tri-mode",
    nameAr: "أتاك شارك X6 PAW3395 26000 DPI ثلاثي الوضع",
    descFr: "Souris gaming tri-mode (filaire, 2.4G, BT5.2). Capteur PAW3395, 26000 DPI.",
    descAr: "فأرة ألعاب ثلاثية الوضع (سلكي، 2.4G، BT5.2). مستشعر PAW3395، 26000 DPI.",
    priceDzd: 9500,
    stock: 5,
    images: ["https://wifidjelfa.com/wp-content/uploads/2024/07/100949085288136772.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "mouse" },
  },
  {
    slug: "ajazz-aj159-paw3395-wireless-white",
    categorySlug: "mice",
    brand: "AJAZZ",
    nameFr: "AJAZZ AJ159 PAW3395 Sans Fil Blanc",
    nameAr: "أجاز AJ159 PAW3395 لاسلكي أبيض",
    descFr: "Souris gaming sans fil avec capteur PAW3395. Design blanc.",
    descAr: "فأرة ألعاب لاسلكية مع مستشعر PAW3395. تصميم أبيض.",
    priceDzd: 8900,
    stock: 5,
    images: ["https://wifidjelfa.com/wp-content/uploads/2025/08/101502848809828751.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "mouse" },
  },
  {
    slug: "attack-shark-x3-paw3395-trimode",
    categorySlug: "mice",
    brand: "Attack Shark",
    nameFr: "Attack Shark X3 PAW3395 26000 DPI Tri-mode",
    nameAr: "أتاك شارك X3 PAW3395 26000 DPI ثلاثي الوضع",
    descFr: "Souris gaming tri-mode avec capteur PAW3395, 26000 DPI.",
    descAr: "فأرة ألعاب ثلاثية الوضع مع مستشعر PAW3395، 26000 DPI.",
    priceDzd: 8500,
    stock: 6,
    images: ["https://wifidjelfa.com/wp-content/uploads/2025/12/101669562914701518.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "mouse" },
  },

  // ============ HEADSETS ============
  {
    slug: "razer-kraken-v4-x-rgb",
    categorySlug: "headsets",
    brand: "Razer",
    nameFr: "Razer Kraken V4 X Gaming RGB",
    nameAr: "ريزر كراكن V4 X سماعة ألعاب RGB",
    descFr: "Casque gaming Razer Kraken V4 X avec éclairage RGB. Son immersif, micro intégré.",
    descAr: "سماعة ألعاب ريزر كراكن V4 X مع إضاءة RGB. صوت غامر، ميكروفون مدمج.",
    priceDzd: 26500,
    stock: 3,
    images: ["https://wifidjelfa.com/wp-content/uploads/2025/09/101543455930450106.jpg"],
    featured: true,
    specs: { type: "accessory", subtype: "headset" },
  },
  {
    slug: "logitech-g-pro-x-se-wired",
    categorySlug: "headsets",
    brand: "Logitech",
    nameFr: "Logitech G PRO X SE Filaire Gaming",
    nameAr: "لوجيتك G PRO X SE سلكي ألعاب",
    descFr: "Casque gaming filaire Logitech G PRO X SE. Son DTS:X 2.0, micro Blue VO!CE.",
    descAr: "سماعة ألعاب سلكية لوجيتك G PRO X SE. صوت DTS:X 2.0، ميكروفون Blue VO!CE.",
    priceDzd: 24500,
    stock: 4,
    images: ["https://wifidjelfa.com/wp-content/uploads/2025/09/101543455930450125.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "headset" },
  },
  {
    slug: "logitech-g535-lightspeed-wireless",
    categorySlug: "headsets",
    brand: "Logitech",
    nameFr: "Logitech G535 LIGHTSPEED Sans Fil",
    nameAr: "لوجيتك G535 LIGHTSPEED لاسلكي",
    descFr: "Casque gaming sans fil LIGHTSPEED pour PS5/PS4/PC/Mac. Léger et confortable.",
    descAr: "سماعة ألعاب لاسلكية LIGHTSPEED لـ PS5/PS4/PC/Mac. خفيفة ومريحة.",
    priceDzd: 23900,
    stock: 3,
    images: ["https://wifidjelfa.com/wp-content/uploads/2025/09/101543455930450035.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "headset" },
  },
  {
    slug: "razer-kraken-v3-rgb",
    categorySlug: "headsets",
    brand: "Razer",
    nameFr: "Razer Kraken V3 Gaming RGB",
    nameAr: "ريزر كراكن V3 سماعة ألعاب RGB",
    descFr: "Casque gaming Razer Kraken V3 avec éclairage RGB et son THX Spatial Audio.",
    descAr: "سماعة ألعاب ريزر كراكن V3 مع إضاءة RGB وصوت THX Spatial Audio.",
    priceDzd: 22000,
    stock: 4,
    images: ["https://wifidjelfa.com/wp-content/uploads/2025/09/101543455930450101.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "headset" },
  },
  {
    slug: "nzxt-relay-gaming-headset",
    categorySlug: "headsets",
    brand: "NZXT",
    nameFr: "NZXT Relay Gaming Headset Noir/Blanc",
    nameAr: "NZXT Relay سماعة ألعاب أسود/أبيض",
    descFr: "Casque gaming NZXT Relay. Confort premium, son hi-res, micro détachable.",
    descAr: "سماعة ألعاب NZXT Relay. راحة ممتازة، صوت عالي الدقة، ميكروفون قابل للفصل.",
    priceDzd: 21900,
    stock: 3,
    images: ["https://wifidjelfa.com/wp-content/uploads/2026/04/101855071024709663.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "headset" },
  },
  {
    slug: "hyperx-cloud-stinger-2",
    categorySlug: "headsets",
    brand: "HyperX",
    nameFr: "HyperX Cloud Stinger 2 Gaming",
    nameAr: "هايبر إكس كلاود ستينغر 2 ألعاب",
    descFr: "Casque gaming HyperX Cloud Stinger 2. Léger, confortable, son DTS:X.",
    descAr: "سماعة ألعاب HyperX Cloud Stinger 2. خفيفة، مريحة، صوت DTS:X.",
    priceDzd: 21000,
    stock: 5,
    images: ["https://wifidjelfa.com/wp-content/uploads/2025/12/101689911916101729.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "headset" },
  },
  {
    slug: "hyperx-cloud-ii-7-1",
    categorySlug: "headsets",
    brand: "HyperX",
    nameFr: "HyperX Cloud II Gaming 7.1",
    nameAr: "هايبر إكس كلاود II ألعاب 7.1",
    descFr: "Casque gaming HyperX Cloud II avec son surround virtuel 7.1. Micro détachable à réduction de bruit.",
    descAr: "سماعة ألعاب HyperX Cloud II مع صوت محيطي افتراضي 7.1. ميكروفون قابل للفصل.",
    priceDzd: 18400,
    stock: 5,
    images: ["https://wifidjelfa.com/wp-content/uploads/2026/02/101752165034360833.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "headset" },
  },
  {
    slug: "steelseries-nova-1-gaming",
    categorySlug: "headsets",
    brand: "SteelSeries",
    nameFr: "SteelSeries Arctis Nova 1 Gaming",
    nameAr: "ستيل سيريز أركتيس نوفا 1 ألعاب",
    descFr: "Casque gaming SteelSeries Arctis Nova 1. Son haute fidélité, confort longue durée.",
    descAr: "سماعة ألعاب SteelSeries Arctis Nova 1. صوت عالي الدقة، راحة طويلة الأمد.",
    priceDzd: 17900,
    stock: 4,
    images: ["https://wifidjelfa.com/wp-content/uploads/2025/09/101543455930450121.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "headset" },
  },
  {
    slug: "hyperx-cloud-mini-gaming",
    categorySlug: "headsets",
    brand: "HyperX",
    nameFr: "HyperX Cloud Mini Gaming",
    nameAr: "هايبر إكس كلاود ميني ألعاب",
    descFr: "Casque gaming compact HyperX Cloud Mini. Léger, portable, bon son.",
    descAr: "سماعة ألعاب مدمجة HyperX Cloud Mini. خفيفة، محمولة، صوت جيد.",
    priceDzd: 15900,
    stock: 5,
    images: ["https://wifidjelfa.com/wp-content/uploads/2025/09/101543455930450090.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "headset" },
  },
  {
    slug: "spirit-of-gamer-xpert-h1100",
    categorySlug: "headsets",
    brand: "Spirit of Gamer",
    nameFr: "Spirit Of Gamer Xpert-H1100",
    nameAr: "سبيريت أوف غيمر Xpert-H1100",
    descFr: "Casque-micro gaming Spirit Of Gamer Xpert-H1100. Son surround, RGB, confort premium.",
    descAr: "سماعة ألعاب Spirit Of Gamer Xpert-H1100. صوت محيطي، RGB، راحة ممتازة.",
    priceDzd: 13700,
    stock: 4,
    images: ["https://wifidjelfa.com/wp-content/uploads/2026/01/101706070455484629.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "headset" },
  },
  {
    slug: "razer-blackshark-v2-x",
    categorySlug: "headsets",
    brand: "Razer",
    nameFr: "Razer BlackShark V2 X Esports",
    nameAr: "ريزر بلاك شارك V2 X رياضات إلكترونية",
    descFr: "Casque esports Razer BlackShark V2 X. Son TriForce 50mm, micro Hyperclear.",
    descAr: "سماعة رياضات إلكترونية ريزر BlackShark V2 X. صوت TriForce 50mm، ميكروفون Hyperclear.",
    priceDzd: 12500,
    stock: 5,
    images: ["https://wifidjelfa.com/wp-content/uploads/2026/03/101833968206217221.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "headset" },
  },
  {
    slug: "spirit-of-gamer-xpert-h900-wireless",
    categorySlug: "headsets",
    brand: "Spirit of Gamer",
    nameFr: "Spirit Of Gamer Xpert-H900 Sans Fil 2.4GHz",
    nameAr: "سبيريت أوف غيمر Xpert-H900 لاسلكي 2.4GHz",
    descFr: "Casque gaming sans fil 2.4GHz Spirit Of Gamer. Autonomie longue durée.",
    descAr: "سماعة ألعاب لاسلكية 2.4GHz Spirit Of Gamer. بطارية طويلة الأمد.",
    priceDzd: 11400,
    stock: 4,
    images: ["https://wifidjelfa.com/wp-content/uploads/2026/01/101706070455484591.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "headset" },
  },

  // ============ CONTROLLERS ============
  {
    slug: "aolion-al-k10-wireless-purple",
    categorySlug: "controllers",
    brand: "AOLION",
    nameFr: "AOLION AL-K10 Manette Sans Fil Violet",
    nameAr: "AOLION AL-K10 يد تحكم لاسلكية بنفسجي",
    descFr: "Manette de jeu sans fil AOLION AL-K10. Compatible PC/PS/Switch. Design violet.",
    descAr: "يد تحكم لاسلكية AOLION AL-K10. متوافقة مع PC/PS/Switch. تصميم بنفسجي.",
    priceDzd: 12900,
    stock: 5,
    images: ["https://wifidjelfa.com/wp-content/uploads/2025/04/101329227709677596.jpg"],
    featured: true,
    specs: { type: "accessory", subtype: "controller" },
  },
  {
    slug: "aolion-al-k10-wireless-white",
    categorySlug: "controllers",
    brand: "AOLION",
    nameFr: "AOLION AL-K10 Manette Sans Fil Blanc",
    nameAr: "AOLION AL-K10 يد تحكم لاسلكية أبيض",
    descFr: "Manette de jeu sans fil AOLION AL-K10. Compatible PC/PS/Switch. Design blanc.",
    descAr: "يد تحكم لاسلكية AOLION AL-K10. متوافقة مع PC/PS/Switch. تصميم أبيض.",
    priceDzd: 12900,
    stock: 5,
    images: ["https://wifidjelfa.com/wp-content/uploads/2025/04/101329227709677595.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "controller" },
  },
  {
    slug: "gamesir-t7-xbox-wired-red",
    categorySlug: "controllers",
    brand: "GameSir",
    nameFr: "GameSir T7 Manette Filaire Xbox Rouge",
    nameAr: "غيم سير T7 يد تحكم سلكية Xbox أحمر",
    descFr: "Manette filaire GameSir T7 pour Xbox/PC. Design rouge, vibration haptique.",
    descAr: "يد تحكم سلكية GameSir T7 لـ Xbox/PC. تصميم أحمر، اهتزاز لمسي.",
    priceDzd: 9900,
    stock: 4,
    images: ["https://wifidjelfa.com/wp-content/uploads/2025/06/101436158822580289.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "controller" },
  },
  {
    slug: "easysmx-x05-black-hall-effect",
    categorySlug: "controllers",
    brand: "EasySMX",
    nameFr: "EasySMX X05 Noir Hall Effect Multiplateforme",
    nameAr: "EasySMX X05 أسود Hall Effect متعدد المنصات",
    descFr: "Manette multiplateforme avec joysticks Hall Effect. PC/Switch/Android/iOS.",
    descAr: "يد تحكم متعددة المنصات مع عصا تحكم Hall Effect. PC/Switch/Android/iOS.",
    priceDzd: 6900,
    stock: 6,
    images: ["https://wifidjelfa.com/wp-content/uploads/2026/02/101775429664243801.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "controller" },
  },
  {
    slug: "easysmx-x05-white-hall-effect",
    categorySlug: "controllers",
    brand: "EasySMX",
    nameFr: "EasySMX X05 Blanc Hall Effect Multiplateforme",
    nameAr: "EasySMX X05 أبيض Hall Effect متعدد المنصات",
    descFr: "Manette multiplateforme avec joysticks Hall Effect. PC/Switch/Android/iOS. Blanc.",
    descAr: "يد تحكم متعددة المنصات مع عصا تحكم Hall Effect. أبيض.",
    priceDzd: 6900,
    stock: 6,
    images: ["https://wifidjelfa.com/wp-content/uploads/2026/02/101775429664243803.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "controller" },
  },
  {
    slug: "spirit-of-gamer-predator-filaire",
    categorySlug: "controllers",
    brand: "Spirit of Gamer",
    nameFr: "Spirit Of Gamer PREDATOR Filaire PC/PS3/PS4/Android/iOS",
    nameAr: "سبيريت أوف غيمر بريداتور سلكي PC/PS3/PS4",
    descFr: "Manette filaire Spirit Of Gamer PREDATOR. Compatible PC, PS3, PS4, Android, iOS.",
    descAr: "يد تحكم سلكية Spirit Of Gamer PREDATOR. متوافقة مع PC، PS3، PS4، Android، iOS.",
    priceDzd: 5500,
    stock: 5,
    images: ["https://wifidjelfa.com/wp-content/uploads/2025/05/101370403896688651.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "controller" },
  },
  {
    slug: "gaminja-p412-white",
    categorySlug: "controllers",
    brand: "GAMINJA",
    nameFr: "GAMINJA P412 Manette Blanc",
    nameAr: "GAMINJA P412 يد تحكم أبيض",
    descFr: "Manette de jeu GAMINJA P412. Design blanc, compatible multiplateforme.",
    descAr: "يد تحكم GAMINJA P412. تصميم أبيض، متوافقة متعددة المنصات.",
    priceDzd: 4500,
    stock: 6,
    images: ["https://wifidjelfa.com/wp-content/uploads/2025/07/101472454752338017.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "controller" },
  },
  {
    slug: "gaminja-p412-black",
    categorySlug: "controllers",
    brand: "GAMINJA",
    nameFr: "GAMINJA P412 Manette Noir",
    nameAr: "GAMINJA P412 يد تحكم أسود",
    descFr: "Manette de jeu GAMINJA P412. Design noir, compatible multiplateforme.",
    descAr: "يد تحكم GAMINJA P412. تصميم أسود، متوافقة متعددة المنصات.",
    priceDzd: 4300,
    stock: 6,
    images: ["https://wifidjelfa.com/wp-content/uploads/2025/09/101572472544952804.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "controller" },
  },
  {
    slug: "havit-g158bt-pro-wired-gamepad",
    categorySlug: "controllers",
    brand: "HAVIT",
    nameFr: "HAVIT G158BT PRO Manette Filaire Haute Précision",
    nameAr: "HAVIT G158BT PRO يد تحكم سلكية عالية الدقة",
    descFr: "Manette filaire haute précision HAVIT GAMENOTE G158BT PRO.",
    descAr: "يد تحكم سلكية عالية الدقة HAVIT GAMENOTE G158BT PRO.",
    priceDzd: 4300,
    stock: 5,
    images: ["https://wifidjelfa.com/wp-content/uploads/2025/04/101315838971215879.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "controller" },
  },

  // ============ MOUSE PADS ============
  {
    slug: "arctic-liquid-freezer-iii-mousepad",
    categorySlug: "mouse-pads",
    brand: "Arctic",
    nameFr: "Tapis Arctic Liquid Freezer III Edition 400x900mm",
    nameAr: "لوحة فأرة أركتيك Liquid Freezer III 400x900mm",
    descFr: "Tapis de souris grand format 400x900x3mm édition spéciale Liquid Freezer III.",
    descAr: "لوحة فأرة كبيرة الحجم 400x900x3mm إصدار خاص Liquid Freezer III.",
    priceDzd: 5900,
    stock: 4,
    images: ["https://wifidjelfa.com/wp-content/uploads/2025/07/101459509939011627.jpg"],
    featured: true,
    specs: { type: "accessory", subtype: "mousepad" },
  },
  {
    slug: "spirit-of-gamer-victory-bleu-xl",
    categorySlug: "mouse-pads",
    brand: "Spirit of Gamer",
    nameFr: "Spirit Of Gamer Victory Bleu Taille XL 320x430mm",
    nameAr: "سبيريت أوف غيمر Victory أزرق XL 320x430mm",
    descFr: "Tapis de souris Spirit Of Gamer Victory Bleu. Taille XL 320x430mm.",
    descAr: "لوحة فأرة Spirit Of Gamer Victory أزرق. مقاس XL 320x430mm.",
    priceDzd: 2750,
    stock: 6,
    images: ["https://wifidjelfa.com/wp-content/uploads/2025/02/101243411310313495-350x350.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "mousepad" },
  },
  {
    slug: "mars-gaming-mousepad-rgb-365x265",
    categorySlug: "mouse-pads",
    brand: "Mars Gaming",
    nameFr: "Mars Gaming MMPRGBL RGB 365x265mm",
    nameAr: "مارس غيمنغ MMPRGBL RGB 365x265mm",
    descFr: "Tapis de souris RGB Mars Gaming 365x265mm. Éclairage ambiant.",
    descAr: "لوحة فأرة RGB Mars Gaming 365x265mm. إضاءة محيطية.",
    priceDzd: 2450,
    stock: 5,
    images: ["https://wifidjelfa.com/wp-content/uploads/2023/08/100467883376640016-350x350.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "mousepad" },
  },
  {
    slug: "mousepad-purple-wave-300x800",
    categorySlug: "mouse-pads",
    brand: "Generic",
    nameFr: "Tapis Purple Wave 300x800x3mm",
    nameAr: "لوحة فأرة Purple Wave 300x800x3mm",
    descFr: "Tapis de souris grand format 300x800x3mm. Design Purple Wave.",
    descAr: "لوحة فأرة كبيرة الحجم 300x800x3mm. تصميم Purple Wave.",
    priceDzd: 2000,
    stock: 8,
    images: ["https://wifidjelfa.com/wp-content/uploads/2025/07/101436158822580426.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "mousepad" },
  },
  {
    slug: "havit-mp845-mousepad-700x300",
    categorySlug: "mouse-pads",
    brand: "HAVIT",
    nameFr: "HAVIT HV-MP845 Tapis Gaming 700x300x3mm",
    nameAr: "HAVIT HV-MP845 لوحة فأرة ألعاب 700x300x3mm",
    descFr: "Tapis de souris gaming HAVIT 700x300x3mm. Surface lisse, base antidérapante.",
    descAr: "لوحة فأرة ألعاب HAVIT 700x300x3mm. سطح ناعم، قاعدة مانعة للانزلاق.",
    priceDzd: 1200,
    stock: 8,
    images: ["https://wifidjelfa.com/wp-content/uploads/2025/09/101572472544952796.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "mousepad" },
  },
  {
    slug: "havit-mp861-mousepad-700x300",
    categorySlug: "mouse-pads",
    brand: "HAVIT",
    nameFr: "HAVIT MP861 Tapis Gaming 700x300mm",
    nameAr: "HAVIT MP861 لوحة فأرة ألعاب 700x300mm",
    descFr: "Tapis de souris gaming HAVIT MP861 700x300mm.",
    descAr: "لوحة فأرة ألعاب HAVIT MP861 700x300mm.",
    priceDzd: 1100,
    stock: 8,
    images: ["https://wifidjelfa.com/wp-content/uploads/2025/11/101652165948342348.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "mousepad" },
  },

  // ============ KEYBOARDS (Unitech) ============
  {
    slug: "havit-kb902l-mechanical-rgb",
    categorySlug: "keyboards",
    brand: "HAVIT",
    nameFr: "HAVIT KB902L Mécanique RGB",
    nameAr: "هافيت KB902L ميكانيكي RGB",
    descFr: "Clavier mécanique gaming HAVIT KB902L avec rétroéclairage RGB. Switches mécaniques durables.",
    descAr: "كيبورد ميكانيكي للألعاب HAVIT KB902L مع إضاءة خلفية RGB. مفاتيح ميكانيكية متينة.",
    priceDzd: 11900,
    stock: 5,
    images: ["https://unitech-dz.com/wp-content/uploads/2025/05/10kbnujPInNBNd9Quod5bjdA0WKlSHOurTT7M1eS-300x300.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "keyboard" },
  },
  {
    slug: "havit-kb899l-mechanical",
    categorySlug: "keyboards",
    brand: "HAVIT",
    nameFr: "HAVIT KB899L Mécanique Gaming",
    nameAr: "هافيت KB899L ميكانيكي ألعاب",
    descFr: "Clavier mécanique gaming HAVIT KB899L. Design compact, switches réactifs.",
    descAr: "كيبورد ميكانيكي للألعاب HAVIT KB899L. تصميم مدمج، مفاتيح سريعة الاستجابة.",
    priceDzd: 11000,
    stock: 5,
    images: ["https://unitech-dz.com/wp-content/uploads/2025/05/1_8d166f05-c158-44d5-bcc9-c3299081d93e-300x300.webp"],
    featured: false,
    specs: { type: "accessory", subtype: "keyboard" },
  },
  {
    slug: "havit-kb885l-gaming",
    categorySlug: "keyboards",
    brand: "HAVIT",
    nameFr: "HAVIT KB885L Gaming",
    nameAr: "هافيت KB885L ألعاب",
    descFr: "Clavier gaming HAVIT KB885L. Touches réactives, design ergonomique.",
    descAr: "كيبورد ألعاب HAVIT KB885L. مفاتيح سريعة الاستجابة، تصميم مريح.",
    priceDzd: 7900,
    stock: 6,
    images: ["https://unitech-dz.com/wp-content/uploads/2023/08/Capture-decran-4-300x300.png"],
    featured: false,
    specs: { type: "accessory", subtype: "keyboard" },
  },
  {
    slug: "havit-903l-pro-mechanical-blue-white",
    categorySlug: "keyboards",
    brand: "HAVIT",
    nameFr: "HAVIT 903L PRO Mécanique Bleu/Blanc",
    nameAr: "هافيت 903L PRO ميكانيكي أزرق/أبيض",
    descFr: "Clavier mécanique HAVIT 903L PRO. Design bleu et blanc, switches mécaniques.",
    descAr: "كيبورد ميكانيكي HAVIT 903L PRO. تصميم أزرق وأبيض، مفاتيح ميكانيكية.",
    priceDzd: 6900,
    stock: 5,
    images: ["https://unitech-dz.com/wp-content/uploads/2025/05/HAVIT-MECANIQUE-KB877-BLUE-1-1-300x300.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "keyboard" },
  },
  {
    slug: "havit-kb870l-mechanical",
    categorySlug: "keyboards",
    brand: "HAVIT",
    nameFr: "HAVIT KB870L Mécanique Gaming",
    nameAr: "هافيت KB870L ميكانيكي ألعاب",
    descFr: "Clavier mécanique gaming HAVIT KB870L. Compact, réactif, durable.",
    descAr: "كيبورد ميكانيكي للألعاب HAVIT KB870L. مدمج، سريع الاستجابة، متين.",
    priceDzd: 6500,
    stock: 6,
    images: ["https://unitech-dz.com/wp-content/uploads/2023/03/9QDV4Q2CXJs72oSJZmK39nB7zfZPM0qYEm1tg1Qr-300x300.png"],
    featured: false,
    specs: { type: "accessory", subtype: "keyboard" },
  },
  {
    slug: "havit-890l-mechanical",
    categorySlug: "keyboards",
    brand: "HAVIT",
    nameFr: "HAVIT 890L Mécanique Gaming",
    nameAr: "هافيت 890L ميكانيكي ألعاب",
    descFr: "Clavier mécanique gaming HAVIT 890L. Entrée de gamme fiable.",
    descAr: "كيبورد ميكانيكي للألعاب HAVIT 890L. فئة اقتصادية موثوقة.",
    priceDzd: 5900,
    stock: 6,
    images: ["https://unitech-dz.com/wp-content/uploads/2025/05/65A3FFDD3EE5C-300x300.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "keyboard" },
  },

  // ============ MICE (Unitech) ============
  {
    slug: "galax-slider-05-rgb",
    categorySlug: "mice",
    brand: "GALAX",
    nameFr: "GALAX Slider-05 RGB Gaming",
    nameAr: "جالاكس Slider-05 RGB ألعاب",
    descFr: "Souris gaming GALAX Slider-05 avec éclairage RGB. Capteur optique précis.",
    descAr: "فأرة ألعاب GALAX Slider-05 مع إضاءة RGB. مستشعر بصري دقيق.",
    priceDzd: 8500,
    stock: 5,
    images: ["https://unitech-dz.com/wp-content/uploads/2025/02/GALAX-SLIDER-05-RGB-GAMING-MOUSE-OPTICAL-5-300x300.png"],
    featured: false,
    specs: { type: "accessory", subtype: "mouse" },
  },
  {
    slug: "redragon-m901-gaming-rgb",
    categorySlug: "mice",
    brand: "Redragon",
    nameFr: "Redragon M901 Gaming RGB",
    nameAr: "ريد دراغون M901 ألعاب RGB",
    descFr: "Souris gaming Redragon M901 avec éclairage RGB. 12400 DPI, 18 boutons programmables.",
    descAr: "فأرة ألعاب Redragon M901 مع إضاءة RGB. 12400 DPI، 18 زر قابل للبرمجة.",
    priceDzd: 6500,
    stock: 5,
    images: ["https://unitech-dz.com/wp-content/uploads/2025/02/61WcRMMZ65L._AC_SL1500_-300x300.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "mouse" },
  },
  {
    slug: "redragon-m908-impact-rgb",
    categorySlug: "mice",
    brand: "Redragon",
    nameFr: "Redragon M908 Impact RGB",
    nameAr: "ريد دراغون M908 إمباكت RGB",
    descFr: "Souris gaming Redragon M908 Impact avec éclairage RGB. 12400 DPI, 12 boutons latéraux.",
    descAr: "فأرة ألعاب Redragon M908 Impact مع إضاءة RGB. 12400 DPI، 12 زر جانبي.",
    priceDzd: 5900,
    stock: 5,
    images: ["https://unitech-dz.com/wp-content/uploads/2025/02/61kI0PIuXVL._AC_SL1500_-300x300.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "mouse" },
  },
  {
    slug: "magma-swip-s01-gaming",
    categorySlug: "mice",
    brand: "Magma",
    nameFr: "Magma SWIP S01 Gaming",
    nameAr: "ماغما SWIP S01 ألعاب",
    descFr: "Souris gaming Magma SWIP S01. Design ergonomique, capteur précis.",
    descAr: "فأرة ألعاب Magma SWIP S01. تصميم مريح، مستشعر دقيق.",
    priceDzd: 4900,
    stock: 5,
    images: ["https://unitech-dz.com/wp-content/uploads/2025/02/Capture-decran-129-300x300.png"],
    featured: false,
    specs: { type: "accessory", subtype: "mouse" },
  },
  {
    slug: "spirit-of-gamer-pro-m7-rgb",
    categorySlug: "mice",
    brand: "Spirit of Gamer",
    nameFr: "Spirit Of Gamer PRO M-7 RGB",
    nameAr: "سبيريت أوف غيمر PRO M-7 RGB",
    descFr: "Souris gaming Spirit Of Gamer PRO M-7 avec éclairage RGB.",
    descAr: "فأرة ألعاب Spirit Of Gamer PRO M-7 مع إضاءة RGB.",
    priceDzd: 4200,
    stock: 5,
    images: ["https://unitech-dz.com/wp-content/uploads/2024/11/souris-pro-m7-300x300.png"],
    featured: false,
    specs: { type: "accessory", subtype: "mouse" },
  },
  {
    slug: "msi-forge-gm300-gaming-rgb",
    categorySlug: "mice",
    brand: "MSI",
    nameFr: "MSI Forge GM300 Gaming RGB",
    nameAr: "MSI Forge GM300 ألعاب RGB",
    descFr: "Souris gaming MSI Forge GM300 avec éclairage RGB. Capteur optique haute précision.",
    descAr: "فأرة ألعاب MSI Forge GM300 مع إضاءة RGB. مستشعر بصري عالي الدقة.",
    priceDzd: 3900,
    stock: 6,
    images: ["https://unitech-dz.com/wp-content/uploads/2025/02/1-300x300.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "mouse" },
  },
  {
    slug: "msi-forge-gm100-gaming-rgb",
    categorySlug: "mice",
    brand: "MSI",
    nameFr: "MSI Forge GM100 Gaming RGB",
    nameAr: "MSI Forge GM100 ألعاب RGB",
    descFr: "Souris gaming MSI Forge GM100. RGB, légère, idéale pour débuter.",
    descAr: "فأرة ألعاب MSI Forge GM100. RGB، خفيفة، مثالية للمبتدئين.",
    priceDzd: 3900,
    stock: 6,
    images: ["https://unitech-dz.com/wp-content/uploads/2025/02/product-300x300.png"],
    featured: false,
    specs: { type: "accessory", subtype: "mouse" },
  },

  // ============ HEADSETS (Unitech) ============
  {
    slug: "havit-fuxi-h7-5modes-white",
    categorySlug: "headsets",
    brand: "HAVIT",
    nameFr: "HAVIT FUXI H7 5 Modes Sans Fil Blanc",
    nameAr: "هافيت FUXI H7 5 أوضاع لاسلكي أبيض",
    descFr: "Casque gaming HAVIT FUXI H7 avec 5 modes de connexion. Design blanc, son immersif.",
    descAr: "سماعة ألعاب HAVIT FUXI H7 مع 5 أوضاع اتصال. تصميم أبيض، صوت غامر.",
    priceDzd: 12900,
    stock: 4,
    images: ["https://unitech-dz.com/wp-content/uploads/2025/09/CASQUE-GAMER-HAVIT-FUXI-H7-FIVE-MODE-WHITE-300x300.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "headset" },
  },
  {
    slug: "havit-fuxi-h7-5modes-black",
    categorySlug: "headsets",
    brand: "HAVIT",
    nameFr: "HAVIT FUXI H7 5 Modes Sans Fil Noir",
    nameAr: "هافيت FUXI H7 5 أوضاع لاسلكي أسود",
    descFr: "Casque gaming HAVIT FUXI H7 avec 5 modes de connexion. Design noir, son immersif.",
    descAr: "سماعة ألعاب HAVIT FUXI H7 مع 5 أوضاع اتصال. تصميم أسود، صوت غامر.",
    priceDzd: 12900,
    stock: 4,
    images: ["https://unitech-dz.com/wp-content/uploads/2025/09/imagSes.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "headset" },
  },
  {
    slug: "havit-h2002d-white",
    categorySlug: "headsets",
    brand: "HAVIT",
    nameFr: "HAVIT H2002D Gaming Blanc",
    nameAr: "هافيت H2002D ألعاب أبيض",
    descFr: "Casque gaming HAVIT H2002D. Son surround, micro intégré, design blanc.",
    descAr: "سماعة ألعاب HAVIT H2002D. صوت محيطي، ميكروفون مدمج، تصميم أبيض.",
    priceDzd: 6500,
    stock: 5,
    images: ["https://unitech-dz.com/wp-content/uploads/2025/09/D_NQ_NP_2X_671220-MLU77171929674_072024-F-600x598-1-300x300.webp"],
    featured: false,
    specs: { type: "accessory", subtype: "headset" },
  },
  {
    slug: "havit-h2002d-black",
    categorySlug: "headsets",
    brand: "HAVIT",
    nameFr: "HAVIT H2002D Gaming Noir",
    nameAr: "هافيت H2002D ألعاب أسود",
    descFr: "Casque gaming HAVIT H2002D. Son surround, micro intégré, design noir.",
    descAr: "سماعة ألعاب HAVIT H2002D. صوت محيطي، ميكروفون مدمج، تصميم أسود.",
    priceDzd: 6500,
    stock: 5,
    images: ["https://unitech-dz.com/wp-content/uploads/2025/09/CASQUE-HAVIT-GAMING-H2002D-1-300x300.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "headset" },
  },
  {
    slug: "havit-h2027u-gaming",
    categorySlug: "headsets",
    brand: "HAVIT",
    nameFr: "HAVIT H2027U Gaming USB",
    nameAr: "هافيت H2027U ألعاب USB",
    descFr: "Casque gaming HAVIT H2027U USB. Son 7.1 virtuel, micro flexible.",
    descAr: "سماعة ألعاب HAVIT H2027U USB. صوت 7.1 افتراضي، ميكروفون مرن.",
    priceDzd: 6000,
    stock: 5,
    images: ["https://unitech-dz.com/wp-content/uploads/2021/01/1-300x300.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "headset" },
  },
  {
    slug: "havit-h2033d-gaming",
    categorySlug: "headsets",
    brand: "HAVIT",
    nameFr: "HAVIT H2033D Gaming",
    nameAr: "هافيت H2033D ألعاب",
    descFr: "Casque gaming HAVIT H2033D. Confortable, micro anti-bruit, RGB.",
    descAr: "سماعة ألعاب HAVIT H2033D. مريحة، ميكروفون عازل للضوضاء، RGB.",
    priceDzd: 5800,
    stock: 6,
    images: ["https://unitech-dz.com/wp-content/uploads/2025/09/HAVIT-H2033d-1-9-300x300.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "headset" },
  },
  {
    slug: "gameon-got100a-thunderstrike",
    categorySlug: "headsets",
    brand: "GameOn",
    nameFr: "GameOn GOT100A Thunderstrike",
    nameAr: "غيم أون GOT100A ثاندرسترايك",
    descFr: "Casque gaming GameOn Thunderstrike GOT100A. Son stéréo, micro intégré.",
    descAr: "سماعة ألعاب GameOn Thunderstrike GOT100A. صوت ستيريو، ميكروفون مدمج.",
    priceDzd: 5200,
    stock: 5,
    images: ["https://unitech-dz.com/wp-content/uploads/2025/02/ac52d250-64d0-44af-ad52-3095c6343f28-1000x999.3220338983-cKJONfB7Rt2enYKcPEpbAUtXe78xP304VL6bKECw-300x300.png"],
    featured: false,
    specs: { type: "accessory", subtype: "headset" },
  },
  {
    slug: "gameon-got200a-thunderstrike-rgb",
    categorySlug: "headsets",
    brand: "GameOn",
    nameFr: "GameOn GOT200A Thunderstrike RGB Noir",
    nameAr: "غيم أون GOT200A ثاندرسترايك RGB أسود",
    descFr: "Casque gaming GameOn Thunderstrike GOT200A RGB. Éclairage RGB, son immersif.",
    descAr: "سماعة ألعاب GameOn Thunderstrike GOT200A RGB. إضاءة RGB، صوت غامر.",
    priceDzd: 4900,
    stock: 5,
    images: ["https://unitech-dz.com/wp-content/uploads/2025/02/uae_gameon-got200a-thunderstrike-rgb-gaming-headset-black_0-300x300.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "headset" },
  },
  {
    slug: "havit-h659d-gaming",
    categorySlug: "headsets",
    brand: "HAVIT",
    nameFr: "HAVIT H659D Gaming",
    nameAr: "هافيت H659D ألعاب",
    descFr: "Casque gaming HAVIT H659D. Son clair, micro flexible, confortable.",
    descAr: "سماعة ألعاب HAVIT H659D. صوت واضح، ميكروفون مرن، مريحة.",
    priceDzd: 4000,
    stock: 6,
    images: ["https://unitech-dz.com/wp-content/uploads/2023/08/havit-hv-h659d-wired-gaming-headphone-01-500x500-1-300x300.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "headset" },
  },
  {
    slug: "havit-h2042-gaming",
    categorySlug: "headsets",
    brand: "HAVIT",
    nameFr: "HAVIT H2042 Gaming",
    nameAr: "هافيت H2042 ألعاب",
    descFr: "Casque gaming HAVIT H2042. Bon rapport qualité-prix, micro intégré.",
    descAr: "سماعة ألعاب HAVIT H2042. قيمة جيدة مقابل السعر، ميكروفون مدمج.",
    priceDzd: 3900,
    stock: 6,
    images: ["https://unitech-dz.com/wp-content/uploads/2024/07/53360615_25-06-2024_6060-300x300.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "headset" },
  },
  {
    slug: "havit-h2040d-gaming",
    categorySlug: "headsets",
    brand: "HAVIT",
    nameFr: "HAVIT H2040D Gaming",
    nameAr: "هافيت H2040D ألعاب",
    descFr: "Casque gaming HAVIT H2040D. Léger, confortable, entrée de gamme.",
    descAr: "سماعة ألعاب HAVIT H2040D. خفيف، مريح، فئة اقتصادية.",
    priceDzd: 3500,
    stock: 6,
    images: ["https://unitech-dz.com/wp-content/uploads/2025/09/237068618_25-06-2024_258799-300x300.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "headset" },
  },
  {
    slug: "havit-h2263d-gaming",
    categorySlug: "headsets",
    brand: "HAVIT",
    nameFr: "HAVIT H2263D Gaming",
    nameAr: "هافيت H2263D ألعاب",
    descFr: "Casque gaming HAVIT H2263D. Ultra abordable, son correct, micro intégré.",
    descAr: "سماعة ألعاب HAVIT H2263D. سعر منخفض جداً، صوت جيد، ميكروفون مدمج.",
    priceDzd: 2200,
    stock: 8,
    images: ["https://unitech-dz.com/wp-content/uploads/2024/06/1-8-300x300.png"],
    featured: false,
    specs: { type: "accessory", subtype: "headset" },
  },

  // ============ CONTROLLERS (Unitech) ============
  {
    slug: "havit-g180bt-transparent",
    categorySlug: "controllers",
    brand: "HAVIT",
    nameFr: "HAVIT G180BT Manette Transparente",
    nameAr: "هافيت G180BT يد تحكم شفافة",
    descFr: "Manette de jeu HAVIT G180BT transparente. Design unique, compatible multiplateforme.",
    descAr: "يد تحكم HAVIT G180BT شفافة. تصميم فريد، متوافقة متعددة المنصات.",
    priceDzd: 4200,
    stock: 5,
    images: ["https://unitech-dz.com/wp-content/uploads/2025/05/cGIJofNyGLj3cnzNDF3mlA6mOeb8w88trAMbTDT0-300x300.png"],
    featured: false,
    specs: { type: "accessory", subtype: "controller" },
  },
  {
    slug: "havit-g158bt-pro-transparent",
    categorySlug: "controllers",
    brand: "HAVIT",
    nameFr: "HAVIT G158BT PRO Manette Transparente",
    nameAr: "هافيت G158BT PRO يد تحكم شفافة",
    descFr: "Manette de jeu HAVIT G158BT PRO transparente. Haute précision, design moderne.",
    descAr: "يد تحكم HAVIT G158BT PRO شفافة. دقة عالية، تصميم عصري.",
    priceDzd: 4000,
    stock: 5,
    images: ["https://unitech-dz.com/wp-content/uploads/2025/05/38yRXqZ6ZvnYtT4iaI20cRkmDDrcUHh1BhTtT7pc-300x300.png"],
    featured: false,
    specs: { type: "accessory", subtype: "controller" },
  },

  // ============ MOUSE PADS (Unitech) ============
  {
    slug: "magma-mousepad-rgb-90x40",
    categorySlug: "mouse-pads",
    brand: "Magma",
    nameFr: "Magma Tapis RGB 900x400mm",
    nameAr: "ماغما لوحة فأرة RGB 900x400mm",
    descFr: "Tapis de souris gaming Magma RGB 900x400mm. Éclairage ambiant, surface lisse.",
    descAr: "لوحة فأرة ألعاب Magma RGB 900x400mm. إضاءة محيطية، سطح ناعم.",
    priceDzd: 4200,
    stock: 5,
    images: ["https://unitech-dz.com/wp-content/uploads/2024/09/Capture-decran-91-300x300.png"],
    featured: false,
    specs: { type: "accessory", subtype: "mousepad" },
  },
  {
    slug: "havit-mp830-xl-mousepad",
    categorySlug: "mouse-pads",
    brand: "HAVIT",
    nameFr: "HAVIT MP830 Tapis Extra Large",
    nameAr: "هافيت MP830 لوحة فأرة كبيرة جداً",
    descFr: "Tapis de souris extra large HAVIT MP830. Surface optimisée, base antidérapante.",
    descAr: "لوحة فأرة كبيرة جداً HAVIT MP830. سطح محسّن، قاعدة مانعة للانزلاق.",
    priceDzd: 1500,
    stock: 8,
    images: ["https://unitech-dz.com/wp-content/uploads/2025/05/hv-mp830-extra-long-mouse-pad-8-1-300x300.jpg"],
    featured: false,
    specs: { type: "accessory", subtype: "mousepad" },
  },
];

export default mutation({
  args: {},
  handler: async (ctx) => {
    // Clear existing
    const existing = await ctx.db.query("products").collect();
    for (const p of existing) await ctx.db.delete(p._id);
    const existingCats = await ctx.db.query("categories").collect();
    for (const c of existingCats) await ctx.db.delete(c._id);

    // Insert categories (hierarchical)
    const catIds: Record<string, any> = {};
    for (const parent of HIERARCHY) {
      const { children, ...parentData } = parent;
      const parentId = await ctx.db.insert("categories", parentData);
      catIds[parent.slug] = parentId;
      for (const child of children) {
        catIds[child.slug] = await ctx.db.insert("categories", {
          ...child,
          parentId,
        });
      }
    }

    // Insert products
    for (const p of PRODUCTS) {
      const { categorySlug, ...rest } = p;
      await ctx.db.insert("products", {
        ...rest,
        categoryId: catIds[categorySlug],
        createdAt: Date.now(),
      });
    }

    const totalCats = HIERARCHY.reduce((sum, p) => sum + 1 + p.children.length, 0);
    return { categories: totalCats, products: PRODUCTS.length };
  },
});
